Makefile.defines, Makefile.rules_generic
Cherry-pick from https://github.com/LedgerHQ/ledger-secure-sdk/pull/164
=> API_LEVEL_1: Makefiles: Rename TARGET_DIR in TARGET_BUILD_DIR

Makefile.defines, Makefile.rules_generic
Cherry-pick from https://github.com/LedgerHQ/ledger-secure-sdk/pull/164
=> API_LEVEL_2: Makefiles: Rename TARGET_DIR in TARGET_BUILD_DIR

lib_nbgl/fonts/nbgl_fonts.c
=> Stax: fix bad unicode parsing

lib_nbgl/include/nbgl_types.h, lib_nbgl/src/nbgl_layout.c, lib_nbgl/src/nbgl_use_case.c
https://ledgerhq.atlassian.net/browse/FWEO-800
=> Stax: Integration of partial waveforms into nbgl use case flows

Makefile.rules, include/errors.h, include/os_io_seproxyhal.h, lib_nfc/include/nfc.h, lib_nfc/src/nfc.c, src/os_io_seproxyhal.c
Add suuport for NDEF uri API
None
=> FWEO-807: add ndef uri api support

lib_bagl/src/bagl.c, lib_nbgl/fonts/nbgl_fonts.c, lib_ux/src/ux_layout_paging_compute.c
This PR removes some clang warnings.
=> Remove clang warning

lib_bagl/src/bagl.c, lib_nbgl/fonts/nbgl_fonts.c, lib_ux/src/ux_layout_paging_compute.c
(cherry picked from commit 6e4173bc0cfe397d448c9172bccef4b9e4b66ecf)
=> Fix issue with UTF-8 decoding (ticket #1749)

lib_nfc/src/nfc.c
=> fix nfc length confusion

src/checks.c
Add the pending review screen for stax
=> checks: add stax audit ux

src/checks.c
Cherry picks https://github.com/LedgerHQ/ledger-secure-sdk/pull/198
=> cherrypick: checks: add stax audit ux 

.github/workflows/check_clang_static_analyzer.yml, lib_bagl/include/bagl_animate.h, lib_bagl/src/bagl.c, lib_bagl/src/bagl_animate.c, lib_nbgl/fonts/nbgl_fonts.c, src/os_io_seproxyhal.c
Cherry-picks from https://github.com/LedgerHQ/ledger-secure-sdk/pull/201
- Add a workflow running Clang static anaylzer.
- Fix existing warnings and errors.
=> Cherry-pick: API_LEVEL_5: Add Clang check and fix Clang issues

include/os_id.h, include/syscalls.h, src/syscalls.c
=> Add a syscall to read the factory settings

.github/workflows/check_clang_static_analyzer.yml, src/os.c, src/os_printf.c
Cherry-picks from https://github.com/LedgerHQ/ledger-secure-sdk/pull/206
=> Cherry-pick: API_LEVEL_6: Fix build warnings when printf

.github/workflows/check_clang_static_analyzer.yml, src/os.c, src/os_printf.c
Cherry-picks from https://github.com/LedgerHQ/ledger-secure-sdk/pull/206
=> Cherry-pick: API_LEVEL_5: Fix build warnings when printf

lib_cxng/include/lcx_hmac.h
Fix an issue with hashing
- [ X] Breaking change (change that is not backwards-compatible and/or changes current functionality)
cxlib changes
=> Fix cxhash structs

lib_nbgl/include/nbgl_use_case.h, lib_nbgl/src/nbgl_layout.c, lib_nbgl/src/nbgl_obj.c, lib_nbgl/src/nbgl_use_case.c
Fixes https://ledgerhq.atlassian.net/browse/FWEO-848 by adjusting some spacing, colors...
It also includes a change in Use Case layer, making some internal functions/constants public, following some App developers demands
=> Stax design adjustements following review

lib_nbgl/fonts/nbgl_fonts.c, lib_nbgl/include/nbgl_draw.h, lib_nbgl/include/nbgl_fonts.h, lib_nbgl/include/nbgl_front.h, lib_nbgl/include/nbgl_layout.h, lib_nbgl/include/nbgl_obj.h, lib_nbgl/include/nbgl_page.h, lib_nbgl/include/nbgl_screen.h, lib_nbgl/include/nbgl_use_case.h, lib_nbgl/src/nbgl_draw.c, lib_nbgl/src/nbgl_layout.c, lib_nbgl/src/nbgl_obj.c, lib_nbgl/src/nbgl_obj_keyboard.c, lib_nbgl/src/nbgl_page.c, lib_nbgl/src/nbgl_screen.c, lib_nbgl/src/nbgl_serialize.c, lib_nbgl/src/nbgl_use_case.c
Add `const` qualifier where needed and remove some not necessary anymore cast dropping `const` qualifier.
=> NBGL const qualifier cleanup

lib_nbgl/include/nbgl_use_case.h
lib_nbgl: Add NB_MAX_DISPLAYED_PAIRS_IN_REVIEW so that it can be used by apps instead of having to define it in the app code with arbitrary value.
=> lib_nbgl: Add NB_MAX_DISPLAYED_PAIRS_IN_REVIEW

include/errors.h
(cherry picked from commit 05579acd15845699145f3b001b5d3136a1713b6b)
=> Add a security error code

include/errors.h
=> Add new error code SWO_APD_STA_38

.github/workflows/build_all_apps.yml
Workflow file to trigger a build on all apps with a given SDK ref
=> Build app in ci

.github/workflows/build_all_apps.yml, .github/workflows/check_clang_static_analyzer.yml, Makefile.defines, Makefile.rules_generic, src/os_printf.c
Contains commits from:
- #237 
- #240
- #219
- #242
- #244 
- #249
=> API_LEVEL_7: Cherry picks

.github/workflows/build_all_apps.yml, .github/workflows/check_clang_static_analyzer.yml, Makefile.defines, Makefile.rules_generic, src/os_printf.c
Contains commits from:
- https://github.com/LedgerHQ/ledger-secure-sdk/pull/237
- https://github.com/LedgerHQ/ledger-secure-sdk/pull/240
- https://github.com/LedgerHQ/ledger-secure-sdk/pull/219
- https://github.com/LedgerHQ/ledger-secure-sdk/pull/242
- https://github.com/LedgerHQ/ledger-secure-sdk/pull/244
- #249
=>  API_LEVEL_5: Cherry picks

lib_nbgl/fonts/nbgl_fonts.c, lib_nbgl/include/nbgl_fonts.h, lib_nbgl/include/nbgl_obj.h, lib_nbgl/src/nbgl_layout.c, lib_nbgl/src/nbgl_navigation.c
The goal is to fix a minor issue on navigation bar, which is causing a refresh even when navigation arrow is inactive.
It also includes improvement on nbgl_fonts management (factorization of character retrieval)
=> Nbgl fixes for fonts and navigation

lib_nbgl/fonts/nbgl_fonts.c, lib_nbgl/include/nbgl_fonts.h, lib_nbgl/include/nbgl_obj.h, lib_nbgl/src/nbgl_layout.c, lib_nbgl/src/nbgl_navigation.c
The goal is to fix a minor issue on navigation bar, which is causing a refresh even when navigation arrow is inactive.
It also includes improvement on nbgl_fonts management (factorization of character retrieval) (cherry pick of https://github.com/LedgerHQ/ledger-secure-sdk/pull/250)
=> Nbgl fixes for fonts and navigation api level 7

lib_nbgl/include/nbgl_use_case.h, lib_nbgl/src/nbgl_use_case.c
Add const qualifier to all relevant useCase API functions
=> Add const qualifier to all relevant useCase API functions

src/os_io_seproxyhal.c
=> io: avoid sending a piezo cmd to MCU if status already sent.

lib_blewbxx_impl/src/ledger_ble.c, src/os_io_seproxyhal.c
=> Pr ble piezo cherry pick

README.md
=> add API_LEVEL infos in Readme

include/os_seed.h
Cherry pick of https://github.com/LedgerHQ/ledger-secure-sdk/pull/268
=> API_LEVEL_8: Cherry pick

include/os_seed.h
Cherry pick of https://github.com/LedgerHQ/ledger-secure-sdk/pull/268
=> API_LEVEL_1: Cherry pick

.github/workflows/unit_tests.yml, .gitignore, lib_standard_app/unit-tests/CMakeLists.txt, lib_standard_app/unit-tests/README.md, lib_standard_app/unit-tests/test_apdu_parser.c, lib_standard_app/unit-tests/test_base58.c, lib_standard_app/unit-tests/test_bip32.c, lib_standard_app/unit-tests/test_buffer.c, lib_standard_app/unit-tests/test_format.c, lib_standard_app/unit-tests/test_write.c
Move unit tests from boilerplate-app to SDK
=> lib_standard_app: add unit tests

lib_blewbxx_impl/src/ledger_ble.c
=> BLE: don't update apdu_media when sending next chunks

include/os_utils.h, src/os.c
Usefull for apps started in lib mode
=> Add a FORCE_RESET_BSS_SEGMENT API to reset the BSS segment to 0

lib_stusb_impl/usbd_impl.c
Add forgotten argument to fix warning
=> lib_stusb_impl: fix warning

lib_stusb_impl/usbd_impl.c
=> Fix warnings

lib_nbgl/doc/nbgl_use_case.dox, lib_nbgl/src/nbgl_use_case.c
Update NBGL use case wording to be compliant with the Figma layouts
=> Update NBGL use case wording to be compliant with the Figma reference layouts

Makefile.standard_app
Introduce new helpers for APP_LOAD_PARAMS and icon handling to simplify app makefiles
=> Makefile.standard_app: Introduce new helpers for APP_LOAD_PARAMS and icon handling

.github/workflows/check_clang_static_analyzer.yml, Makefile.rules_generic
Set scan-build target phony add add status report
=> Set scan-build target phony add add status report

lib_nbgl/src/nbgl_use_case.c
nbgl: Increase appDescription buffer size for use case home
=> nbgl: Increase appDescription buffer size for use case home

target/nanos/script.ld, target/nanos2/script.ld, target/nanox/script.ld, target/stax/script.ld
=> add _code & _ecode to encapsulate .text

README.md
=> README: update API_LEVEL

Makefile.standard_app
Makefile.standard_app: Add HAVE_PENDING_REVIEW_SCREEN setting
=> Makefile.standard_app: Add HAVE_PENDING_REVIEW_SCREEN setting

src/syscalls.c
Tell the compiler that os_lib_end is unreachable, and use same method for os_sched_exit
=> Tell the compiler that os_lib_end is unreachable, and use same method for os_sched_exit

include/errors.h
=> add error code

include/os_seed.h, include/syscalls.h, src/syscalls.c
Replace occurrences of 'protect' by 'recover'.
This PR changes the name of some functions
=> Protect to recover

lib_nbgl/src/nbgl_use_case.c
(cherry picked from commit d2a5d3c67089009ba57f29551dc21cd83a4aee93)
#337
=> nbgl: handle long APPNAME for useCaseHome

lib_nbgl/src/nbgl_use_case.c
(cherry picked from commit https://github.com/LedgerHQ/ledger-secure-sdk/commit/d2a5d3c67089009ba57f29551dc21cd83a4aee93)
#337
=> Fix home usecase 11

include/decorators.h, include/os_utils.h, lib_cxng/include/lcx_aes.h, lib_cxng/include/lcx_blake2.h, lib_cxng/include/lcx_des.h, lib_cxng/include/lcx_ecdh.h, lib_cxng/include/lcx_ecdsa.h, lib_cxng/include/lcx_ecfp.h, lib_cxng/include/lcx_ecschnorr.h, lib_cxng/include/lcx_eddsa.h, lib_cxng/include/lcx_groestl.h, lib_cxng/include/lcx_hash.h, lib_cxng/include/lcx_hmac.h, lib_cxng/include/lcx_math.h, lib_cxng/include/lcx_pbkdf2.h, lib_cxng/include/lcx_rsa.h, lib_cxng/include/lcx_sha3.h
Deprecate all cx throwable functions
- [X ] Bugfix (non-breaking change that solves an issue)
- [X ] Documentation
=> Deprecate all cx throwable functions

include/errors.h
=> Add a new error value

include/os_seed.h
=> Deprecate the "os_perso_derive_xx" throwable functions

lib_nbgl/include/nbgl_use_case.h, lib_nbgl/src/nbgl_use_case.c
(cherry picked from commit ef4acca14c38e2651491960cbc4cd7c2cd03909b)
#343
=> nbgl: handle very long app names

include/syscalls.h, src/syscalls.c
os_bolos_custom_ca_get_info() arguments factorization
=> Custom CA syscall simplification

README.md
README.md: Update API_LEVEL branch list
=> README.md: Update API_LEVEL branch list

src/checks.c
=> stax: fix pending review screen wording

lib_standard_app/buffer.c, lib_standard_app/format.c
Removed ignored return value
Use same type in comparison
=> lib_standard_app fixes

lib_nbgl/src/nbgl_fonts.c, lib_nbgl/src/nbgl_layout.c
The goal is to fix an issue in nbgl_getTextNbLinesInWidth(). 
It is linked to https://ledgerhq.atlassian.net/browse/FWEO-947
=> Improve robustness of strings management in NBGL

lib_nbgl/src/nbgl_use_case.c
Update the "skip warning" screen wording according to the design guidelines
Jira ticket : https://ledgerhq.atlassian.net/browse/B2CA-1338
=> Update the "skip warning" screen wording according to the design guidelines

.codespellrc, .pre-commit-config.yaml
Fix codespell issue on font JSON files.
=> CI: Fix codespell

include/errors.h
(cherry picked from commit 70c9f9285286380234d8d99df150f6e3bf046430)
Add an error code.
=> Add state related error code

lib_nbgl/doc/nbgl_screens_objs.dox
Rebased version of https://github.com/LedgerHQ/ledger-secure-sdk/pull/78
=> Fix NBGL doc typo

lib_standard_app/main.c
- lib_standard_app: Remove write on BSS variable when app is called swap mode
- [lib_standard_app: Add spinner screen for stax exchange SIGN_TRANSACTION command
=> lib_standard_app: Swap fix and improvment

Makefile.standard_app, lib_standard_app/debug.c, lib_standard_app/debug.h, lib_standard_app/main.c, src/os.c
Cherry picks from:
- #410 
- #414 
- #415 
- #411
=> Cherry pick for API_LEVEL_12

Makefile.standard_app, lib_standard_app/debug.c, lib_standard_app/debug.h, lib_standard_app/main.c, src/os.c
Cherry picks from:
- #410 
- #414 
- #415 
- #411
=> Cherry pick for API_LEVEL_5

Makefile.standard_app, lib_standard_app/debug.c, lib_standard_app/debug.h, lib_standard_app/main.c, src/os.c
Cherry picks from:
- #410 
- #414 
- #415 
- #411
=> Cherry pick for API_LEVEL_1

.github/workflows/build_all_apps.yml
CI: Update app-flow build path following app refactoring
=> CI: Update app-flow build path following app refactoring

.github/workflows/build_all_apps.yml
Add Eth app in the list of apps to build on Stax target
=> Add Eth app in the list of apps to build on Stax target

src/ledger_assert.c
Introduced in #473, could not even compile.
=> Fix ledger assert compatibility with DISABLE_UI

lib_nbgl/src/nbgl_use_case.c
nbgl: use_case: Memset nav context when starting use cases
=> nbgl: use_case: Memset nav context when starting use cases

include/ledger_assert.h, src/ledger_assert.c
ledger_assert: Fix circular dependency
=> ledger_assert: Fix circular dependency

lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_if.c
=> Fix Scan-Build: Value stored but never Read

Makefile.defines
=> Set API_LEVEL to 15

lib_nbgl/doc/nbgl_page.dox, lib_nbgl/include/nbgl_content.h, lib_nbgl/include/nbgl_flow.h, lib_nbgl/include/nbgl_layout.h, lib_nbgl/include/nbgl_page.h, lib_nbgl/include/nbgl_use_case.h
nbgl: Create dedicated nbgl_content.h
=> nbgl: Create dedicated nbgl_content.h

include/os_customca.h, include/syscalls.h, src/syscalls.c
Enable a custom CA with HAVE_BOLOS_CUSTOMCA.
=> Replace HAVE_BOLOS_NO_CUSTOMCA with HAVE_BOLOS_CUSTOMCA

include/syscalls.h, lib_nbgl/include/nbgl_screen.h, lib_nbgl/include/nbgl_types.h, src/syscalls.c
Add `nbgl_wait_pipeline` syscall.
This syscall is necessary for eink fast interactions.
=> Stax/Europa: Implement display pipelined ops

lib_nbgl/include/nbgl_use_case.h, lib_nbgl/src/nbgl_use_case.c, src/ledger_assert.c
Add new use cases more generic, bundling some previous ones, and being compatible with future LNX / LNSP implementation.
Showcased in https://github.com/LedgerHQ/app-boilerplate/pull/115
=> Nbgl generic use cases

lib_nbgl/include/nbgl_use_case.h, lib_nbgl/src/nbgl_use_case.c, src/ledger_assert.c
Includes all commits from master (as of 2024-03-14) up to the merge commit of https://github.com/LedgerHQ/ledger-secure-sdk/pull/560 (https://github.com/LedgerHQ/ledger-secure-sdk/commit/808514ead57f4f4381b1b11bca5e5d98018f08f4)
So basically contains only commits from #560
=> Cherry pick for API_LEVEL_18

tools/ttf2inc.py
Ajoute un champ 'branch' aux fichiers JSON contenant les strings des différentes langues.
Cela permet aux traducteurs de générer des screenshots à partir d'une branche autre que master.
=> Get branch info from JSON file

lib_nbgl/src/nbgl_layout_keyboard.c
=> Europa:Use partial wf for suggestion buttons swipe

lib_nbgl/serialization/nbgl_lib.py, lib_nbgl/src/nbgl_obj_keyboard.c
The goal of this PR is to fix https://ledgerhq.atlassian.net/browse/FWEO-1047
=> Fix FWEO-1047 - Inverted shift and caps lock icons

.github/workflows/build_all_apps.yml, .github/workflows/check_clang_static_analyzer.yml
Update the apps build CI to get all the apps repos and to use the manifest files to build each app
=> Update the apps build CI (use apps manifests)

lib_nbgl/include/nbgl_layout.h, lib_nbgl/include/nbgl_use_case.h, lib_nbgl/src/nbgl_layout.c, lib_nbgl/src/nbgl_layout_navigation.c, lib_nbgl/src/nbgl_use_case.c
NBGL: Introduce nbgl_useCaseReviewStreamingXXX() API
=> NBGL: Introduce nbgl_useCaseReviewStreamingXXX() API

lib_nbgl/include/nbgl_content.h, lib_nbgl/include/nbgl_use_case.h, lib_nbgl/src/nbgl_use_case.c
nbgl: Add centered tag value feature
Renaming of `force_page_start` into `forcePageStart`, but most don't use it.
=> nbgl: Add centered tag value feature

include/app_config.h, include/os_io.h, include/os_print.h, lib_cxng/src/cx_aes.c, lib_cxng/src/cx_crc16.c, lib_cxng/src/cx_hash.c, lib_cxng/src/cx_sha256.c, lib_nbgl/src/nbgl_fonts.c, lib_nbgl/src/nbgl_obj.c, lib_nbgl/src/nbgl_screen.c, lib_nbgl/tools/icon2glyph.py, src/os.c, src/os_io_task.c, src/os_printf.c
Add OSU definitions when needed
- [X ] New feature (non-breaking change that adds functionality)
=> Add osu defines when needed

lib_cxng/include/lcx_sha256.h
(cherry picked from commit 310e42e840734dbf47e09c009f204a4356a988a9)
=> Extend #ifdef HAVE_SHA224

lib_standard_app/io.h
Remove weak attributes from header file
=> lib_standard_app/io.h: remove WEAK attributes from function declaration

.github/workflows/build_all_apps.yml, .github/workflows/check_clang_static_analyzer.yml, Makefile.app_params, fuzzing/CMakeLists.txt, fuzzing/README.md, fuzzing/fuzzer_apdu_parser.c, fuzzing/fuzzer_base58.c, fuzzing/fuzzer_bip32.c, fuzzing/fuzzer_qrcodegen.c, fuzzing/mock/os_task.c, fuzzing/mock/os_task.h, lib_cxng/include/lcx_sha256.h, lib_standard_app/bip32.c, lib_standard_app/io.h, src/app_metadata.c, target/nanos/script.ld, target/nanos2/script.ld, target/nanox/script.ld, target/stax/script.ld
Includes commits from:
- #544
- #546 
- #553 
- #574 
- #585
- #588
=> API_LEVEL_5: Cherry-Pick

lib_nbgl/include/nbgl_use_case.h, lib_nbgl/src/nbgl_use_case.c
lib_nbgl: nbgl_use_case.c: Fix missing PIC in weird cases
lib_nbgl: nbgl_use_case: Add nbgl_useCaseGeneric{Review, Configuration}
=> lib_nbgl: nbgl_use_case: Add nbgl_useCaseGeneric{Review, Configuration}

lib_nbgl/src/nbgl_layout.c
Fine tune hold to approve timing for Stax
https://ledgerhq.atlassian.net/browse/FWEO-1065
=> Stax: Fine tune hold to approve timing

lib_stusb_impl/u2f_impl.c
Fix build error in the U2F library.
- [X ] Bugfix (non-breaking change that solves an issue)
=> u2f: Fix build error

Makefile.standard_app, lib_nbgl/include/nbgl_draw.h, lib_nbgl/include/nbgl_layout.h, lib_nbgl/include/nbgl_types.h, lib_nbgl/src/nbgl_draw.c, lib_nbgl/src/nbgl_layout.c, lib_nbgl/src/nbgl_layout_internal.h, lib_nbgl/src/nbgl_layout_keyboard.c, lib_nbgl/src/nbgl_layout_keypad.c, lib_nbgl/src/nbgl_obj.c, lib_nbgl/src/nbgl_obj_keyboard.c, lib_nbgl/src/nbgl_screen.c, lib_stusb_impl/usbd_impl.c
Update API LEVEL 18 with latest changes up to #617  PR merged (master branch commit b93f920d7bc4c1a7154ced07af4332e6a497289e
=> Update API LEVEL 18

lib_nbgl/include/nbgl_layout.h
The goal of this PR is to enable using more suggestion buttons on Flex. It helps to fix https://ledgerhq.atlassian.net/browse/FWEO-1088
=> Fix FWEO-1088 - more suggestion buttons on Flex

lib_cxng/src/cx_eddsa.c
Fix unit tests build and variables initialization.
=> Fix eddsa unit tests

lib_nbgl/src/nbgl_layout.c, lib_nbgl/src/nbgl_layout_internal.h, lib_nbgl/src/nbgl_layout_keyboard.c, lib_nbgl/src/nbgl_layout_keypad.c
This PR fixes https://ledgerhq.atlassian.net/browse/FWEO-1125 and https://ledgerhq.atlassian.net/browse/FWEO-1118
=> Fix FWEO-1125 - FLEX - Bug when unlocking during words recovery

lib_nbgl/include/nbgl_use_case.h, lib_nbgl/src/nbgl_use_case.c, lib_ux_sync/include/ux_sync.h, lib_ux_sync/src/ux_sync.c
=> nbgl_use_case: add nbgl_useCaseReviewLight

README.md
=> README.md: Update API LEVELs

lib_nbgl/include/nbgl_obj.h, lib_nbgl/src/nbgl_use_case.c
=> lib_nbgl: Minor comments fix

include/cx_errors.h
=> cx_errors.h: Fix OS build

lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to fix https://ledgerhq.atlassian.net/browse/FWEO-1171, by playing a  "look at me" sound when starting any review
=> Fix FWEO-1171 - App flows should trigger a "look at me" sound when starting review

.github/workflows/build_all_apps.yml, .github/workflows/check_clang_static_analyzer.yml, .github/workflows/pre-commit.yml, .github/workflows/unit_tests.yml
CI: Bump checkout and upload-artifact action version
=> CI: Bump checkout and upload-artifact action version

lib_nbgl/include/nbgl_use_case.h, lib_nbgl/src/nbgl_layout.c, lib_nbgl/src/nbgl_page.c, lib_nbgl/src/nbgl_use_case.c, lib_nbgl/src/nbgl_use_case_nanos.c
The goal of this PR is to add possible skipping when using nbgl_useCaseReviewStreamingXXX()
=> Add possible skipping when using nbgl_useCaseReviewStreamingXXX()

lib_standard_app/main.c
Add WEAK attribute to main functions of standard app
=> Add WEAK attribute to main functions of standard app

lib_bagl/include/bagl_font_rom.inc, lib_nbgl/include/fonts/nbgl_font_rom.inc
This PR will allow to add support for Brazilian/German/Russian/Turkish (BR/DE/RU/TR) languages.
=> Add support for Brazilian/German/Russian/Turkish (BR/DE/RU/TR) languages

README.md
=> README.md: Update API LEVEL documentation

target/nanos2/script.ld, target/nanox/script.ld
script.ld: Fix LNX and LNSP SRAM size
=> script.ld: Fix LNX and LNSP SRAM size

lib_nbgl/src/nbgl_layout.c, lib_nbgl/src/nbgl_layout_navigation.c, lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to align NBGL layout on Stax & Flex Figmas (https://github.com/LedgerHQ/os-design-deliveries/releases/tag/flex_stax-2024-06)
=> Align NBGL layout on Stax & Flex Figmas

README.md, lib_nbgl/src/nbgl_use_case.c, lib_ux_sync/include/ux_sync.h, lib_ux_sync/src/ux_sync.c
=> Update API LEVEL 21

Makefile.target, target/flex/include/bolos_target.h, target/nanos/include/bolos_target.h, target/nanos2/include/bolos_target.h, target/nanox/include/bolos_target.h, target/stax/include/bolos_target.h
Add protection against double definitions for the bolos target.
=> Protect target (name and id) defines

lib_nbgl/include/nbgl_layout.h
6 suggestion buttons did not allow to select specific words from BIP39
=> Flex: Fix number of suggestion buttons

lib_ux_sync/include/ux_sync.h, lib_ux_sync/src/ux_sync.c
Add use case choice to lib_ux_sync.
=> lib_ux_sync : add choice use case.

lib_nbgl/doc/nbgl_use_case.dox
=> Minor nbgl doc fixes

lib_nbgl/include/nbgl_use_case.h, lib_nbgl/src/nbgl_fonts.c, lib_nbgl/src/nbgl_use_case.c
Fix regression on Stax during long message review
=> Cherry-pick nbgl updates

lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to fix https://github.com/LedgerHQ/ledger-secure-sdk/issues/775.
it consists in taking the "skippable" feature into account in the computation of the number of tag/values fitting in a page
=> Fix number of tag/values computation when the review is skippable

include/os_ux.h, include/syscalls.h, src/syscalls.c
Define a new syscall between UX and dashboard.
No impact on applications.
- [ X ] New feature (non-breaking change that adds functionality)
=> Add new syscall os dashboard mailbox

Makefile.defines, Makefile.rules, Makefile.standard_app
=> Full clang standard app build - cherry-pick on API level 21

lib_nbgl/include/nbgl_content.h, lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to create a QR Code type of modal window for Tag/Value alias
=> Create a QR Code type of modal window for Tag/Value alias

Makefile.defines, Makefile.rules_generic, Makefile.standard_app
No impact on apps build (same checksum), removes the need for a flag that was added in #793
=> Cleaned up arguments passed to the assembler

Makefile.defines, Makefile.rules_generic, Makefile.standard_app
=> Cleaned up arguments passed to the assembler - cherry-pick on API level 21

lib_nbgl/src/nbgl_step.c
=> nanox: fix inactivity shutdown issue.

Makefile.defines, Makefile.rules
=> Miscellaneous build changes - API_LEVEL_22

Makefile.defines
=> Miscellaneous build changes

lib_nbgl/doc/nbgl_use_case.dox, lib_nbgl/include/nbgl_use_case.h, lib_nbgl/src/nbgl_use_case.c
https://github.com/LedgerHQ/ledger-secure-sdk/pull/852
=> Port missing W3C fields

Makefile.defines, Makefile.standard_app
No impact on built apps (same `bin/app.sha256`).
=> Simplified target flags

lib_standard_app/io.c, lib_standard_app/main.c, lib_standard_app/swap_entrypoints.h, lib_standard_app/swap_error_code_helpers.c, lib_standard_app/swap_error_code_helpers.h, lib_standard_app/swap_utils.c, lib_standard_app/swap_utils.h
Add swap error code helpers in the SDK
=> Add swap error code helpers in the SDK

lib_standard_app/io.c, lib_standard_app/swap_error_code_helpers.h
Improve documentation for swap error helpers
=> Improve documentation for swap error helpers

lib_nbgl/include/nbgl_obj.h, lib_nbgl/include/nbgl_types.h, lib_nbgl/src/nbgl_draw.c, lib_nbgl/src/nbgl_layout.c, lib_nbgl/src/nbgl_layout_internal.h, lib_nbgl/src/nbgl_layout_keyboard.c, lib_nbgl/src/nbgl_layout_navigation.c, lib_nbgl/src/nbgl_obj.c, lib_nbgl/src/nbgl_obj_keyboard.c, lib_nbgl/src/nbgl_obj_keypad.c
The goal of this PR is to fix wrong include order and to implement a better management of shared constants in NBGL (for future products addition)
=> Fix wrong include order and shared constants in NBGL

lib_nbgl/src/nbgl_use_case_nanos.c
The goal of this PR is to better manage "skip" feature on reviews on Nano-NBGL, by avoiding displaying the intermediate "skip" page just before review approve/refuse
=> Better management of "skip" feature on reviews on Nano-NBGL (API level 22)

lib_nbgl/serialization/nbgl_lib.py
=> nbgl: update nbgl enum for python lib

include/os_seed.h, include/os_ux.h, include/syscalls.h, src/syscalls.c
=> Ux syscall

lib_nbgl/src/nbgl_layout_internal.h
The goal of this PR is to fix partially erased top right icon
=> Fix partially erased top-right icon

lib_nbgl/src/nbgl_use_case.c
(cherry picked from commit 72112f25da0314f1a861b6638555b7fa073e7149)
=> Fix tinyURL in QR Code

include/decorators.h, lib_cxng/src/cx_chacha.c
=> [CX]: Move unit-test from source

lib_nbgl/include/nbgl_content.h, lib_nbgl/src/nbgl_use_case.c, tests/screenshots/src/app/wallet/app_dogecoin_start.c
The goal of this PR is to enable giving a title for opened page when alias is touched in INFO_LIST_ALIAS case
=> Use given title for opened page when alias is touched in INFO_LIST_ALIAS case

include/os_io_seproxyhal.h, include/os_ux.h, include/os_ux_id.h, lib_ux/include/ux_bagl.h, lib_ux_nbgl/ux_nbgl.h, src/os_io_seproxyhal.c, src/syscalls.c
The goal of this PR is to make Apps able to delay lock-screen/power-off when doing some intense process or APDU echanges not involving User actions on device.
=> Delay lock from app

lib_standard_app/main.c
=> Fix catch warning

lib_standard_app/main.c
=> Fix catch warning - API_LEVEL_22

.github/workflows/unit_tests.yml, Makefile.standard_app, include/app_storage.h, lib_standard_app/app_storage.c, lib_standard_app/app_storage_internal.h, lib_standard_app/main.c, target/flex/script.ld, target/nanos2/script.ld, target/nanox/script.ld, target/stax/script.ld, unit-tests/app_storage/CMakeLists.txt, unit-tests/app_storage/README.md, unit-tests/app_storage/app_storage_stubs.c, unit-tests/app_storage/app_storage_stubs.h, unit-tests/app_storage/test_app_storage.c, unit-tests/gen_coverage.sh, unit-tests/lib_nbgl/README.md
Corresponds to https://github.com/LedgerHQ/ledger-secure-sdk/pull/865 (see there all the description).
APP_STORAGE next improvements: https://github.com/LedgerHQ/ledger-secure-sdk/issues/908
=> App storage functionality improvements

lib_nbgl/include/nbgl_types.h, lib_nbgl/src/nbgl_obj.c, lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to fix alignment for refresh and bug in number of switches per page.
=> Fix alignment for refresh and bug in number of switches per page

lib_bagl/src/bagl.c
=> Fix formatting issue in bagl.c

lib_standard_app/main.c
=> Fix catch warning - API_LEVEL_LNS

include/os_io_seproxyhal.h
Add a new tune to the `tune_index_e`.
=> Add Card Connect sound

Makefile.standard_app, lib_standard_app/main.c
Add ENABLE_PARTIAL_SWAP to the standard app
=> Add ENABLE_TESTING_SWAP to the standard app

Makefile.rules, doc/Doxyfile, doc/mainpage.dox, include/errors.h, lib_alloc/doc/mainpage.dox, lib_alloc/mem_alloc.c, lib_alloc/mem_alloc.h, unit-tests/lib_alloc/CMakeLists.txt, unit-tests/lib_alloc/README.md, unit-tests/lib_alloc/test_mem_alloc.c
=> Add dynamic memory allocator - API_LEVEL_22

lib_stusb_impl/usbd_impl.c
Set USB configs for Apex P and M.
=> Apex P/M: Update USB config

lib_nbgl/src/nbgl_use_case.c
Fix B2CA-2105: Add tooltip for Tx check for streaming use case
Fix B2CA-2093: Update sounds for Transaction Check
=> Small fixes for Transaction checks

lib_nbgl/src/nbgl_use_case.c
based on https://github.com/LedgerHQ/ledger-secure-sdk/pull/944
=> Small fixes for Transaction checks - API_LEVEL_22

lib_nbgl/src/nbgl_use_case.c
cherry-pick from https://github.com/LedgerHQ/ledger-secure-sdk/pull/948
=> Fix Tooltip crash or bad display

include/os_id.h
=> Cleanup, not needed in SDK

lib_nbgl/include/nbgl_use_case.h, lib_nbgl/src/nbgl_use_case_nanos.c
Fix `nbgl_useCaseNavigableContent` (only the 1st content was selectable)
Fix `nbgl_useCaseHomeAndSettings`, `nbgl_useCaseGenericConfiguration` and `nbgl_useCaseGenericSettings` with `BARS_LIST` or `CHOICES_LIST`
=> Fix nbgl nano

.github/workflows/unit_tests.yml, Makefile.rules, doc/Doxyfile, doc/mainpage.dox, include/errors.h, lib_alloc/doc/mainpage.dox, lib_alloc/mem_alloc.c, lib_alloc/mem_alloc.h, unit-tests/lib_alloc/CMakeLists.txt, unit-tests/lib_alloc/README.md, unit-tests/lib_alloc/test_mem_alloc.c
=> lib_alloc - API_LEVEL_23

lib_nbgl/include/nbgl_content.h, lib_nbgl/src/nbgl_use_case_nanos.c
The goal of this PR is to support centered info as tag/value pair for Nano review
=> Support centered info as tag/value pair for Nano review

io/include/os_io.h, io/src/os_io.c, io_legacy/src/os_io_legacy.c, src/syscalls.c
=> [IO]: handle SE event when waiting for end of APDU tx.

lib_nbgl/include/nbgl_layout.h, lib_nbgl/src/nbgl_layout.c, lib_nbgl/src/nbgl_obj.c
The goal of this PR is to fix bug in progress-bar redrawing when decreasing to 0 (nothing redrawn)
=> Fix bug in progress-bar redrawing when decreasing to 0

io/include/os_io.h, io/src/os_io.c, io/src/os_io_seph_ux.c, lib_stusb/src/usbd_ledger.c
=> Fix pr io revamp

.github/workflows/build_all_apps.yml, .github/workflows/check_clang_static_analyzer.yml, Makefile.rules, Makefile.rules_generic, lib_standard_app/main.c, lib_standard_app/main_std_app.h
=> Make improvements - API_LEVEL_22

lib_nbgl/tools/bmp2display.py, lib_nbgl/tools/generate_ledgerimg.sh
- Add Apex in `generate_ledgerimg.sh` script
- Simplify `bmp2display` script
=> Apex ledgerimg

lib_nbgl/include/nbgl_layout.h, lib_nbgl/src/nbgl_layout.c, lib_nbgl/src/nbgl_use_case.c, tests/screenshots/Makefile, tests/screenshots/src/main/stubs.c
The goal of this PR is to support more than 2 or 3 pairs in address review, without glitch on screen
=> Support more than 3 pairs in address review

io/include/os_io.h, io/src/os_io.c, io_legacy/include/os_io_legacy.h, io_legacy/src/os_io_legacy.c, lib_standard_app/io.c
- [ * ] Bugfix (non-breaking change that solves an issue)
=> Call NFC reader functions directly from os_io_rx_evt()

lib_stusb/src/usbd_ledger_hid_u2f.c
(cherry picked from commit 9df70b67fe062870ca0f50491c65863d2a04255b)
=> [u2f]: backport API 24 fix

lib_stusb/src/usbd_ledger_webusb.c
=> [winusb]: put the correct winusb interface

io_legacy/include/os_io_legacy.h, lib_nfc/src/nfc_ledger.c, lib_stusb/src/usbd_ledger_hid_u2f.c
Corresponds to and cherry-picks from https://github.com/LedgerHQ/ledger-secure-sdk/pull/1068
=> HID U2F fixes for SK and Clang static analyzer fixes 

io_legacy/src/os_io_legacy.c, lib_nbgl/src/nbgl_layout_keypad.c, lib_nbgl/src/nbgl_use_case_nanos.c
=> [AUTO_UPDATE] Branch API_LEVEL_24

io_legacy/src/os_io_legacy.c, lib_nbgl/src/nbgl_layout_keypad.c, lib_nbgl/src/nbgl_use_case_nanos.c
=> [AUTO_UPDATE] Branch API_LEVEL_25

lib_nbgl/include/nbgl_obj.h
Cherry-pick from https://github.com/LedgerHQ/ledger-secure-sdk/pull/1082
=> Add icon constants definitions

.github/pull_request_template.md, .github/workflows/auto-cherry-pick.yml, .github/workflows/python_tools_checks.yml, .github/workflows/scripts/pr_check.py
=> Fix auto cherry pick

io/include/os_io.h, io/src/os_io.c, io_legacy/include/os_io_legacy_types.h, io_legacy/src/os_io_legacy.c, lib_stusb/include/usbd_ledger_cdc.h, lib_stusb/src/usbd_ledger.c, lib_stusb/src/usbd_ledger_cdc.c
=> Add CDC support in SDK

lib_stusb/include/usbd_ledger_cdc.h, lib_stusb/src/usbd_ledger_cdc.c
=> Use same template for cdc as hid

protocol/src/ledger_protocol.c
=> [protocol]: Handle empty last chunk

lib_stusb/src/usbd_ctlreq.c, lib_stusb/src/usbd_ledger.c, lib_stusb/src/usbd_ledger_webusb.c
=> Spo fix windows webusb

lib_stusb/src/usbd_ctlreq.c, lib_stusb/src/usbd_ledger.c, lib_stusb/src/usbd_ledger_webusb.c
=> Spo fix windows webusb rc2

lib_nbgl/src/nbgl_obj_keyboard_nanos.c
The goal of this PR is to fix usage of keys masking in NBGL keyboard for Nano.
=> Fix usage of keys masking in NBGL keyboard for Nano

lib_nbgl/src/nbgl_layout_keyboard_nanos.c, lib_nbgl/src/nbgl_obj_keyboard_nanos.c
The goal of this PR is to fix missing letter in NBGL keyboard for Nano
=> Fix missing letter in NBGL keyboard for Nano

lib_stusb/src/usbd_ledger.c
=> [lib_stusb]: init profiles when switching between dashboard & apps

lib_nbgl/src/nbgl_layout.c
(cherry picked from commit 10cf12eca28083b2e1af2954996f2a931cb46fc4)
Remember:
- The merge will ALWAYS be a manual …
=> NBGL layout: Fix missing PIC in "addLeftContent"

lib_standard_app/swap_error_code_helpers.h
Small exchange documentation improvement
=> Small exchange documentation improvement

.github/workflows/scripts/pr_check.py
=> Fix inconsistent token auth formats

io/src/os_io.c, lib_stusb/src/usbd_ledger_hid.c
[X] TARGET_API_LEVEL: API_LEVEL_24
Remember: …
=> Add missing signal in hid stack

lib_nbgl/src/nbgl_obj.c, tests/screenshots/src/main/json_scenario.h
This PR improve the way strings are checked and allow detecting when a button is displayed over some text.
=> Be able to check if a button is overlapping some text

lib_nbgl/src/nbgl_use_case.c
Typo
[X] TARGET_API_LEVEL: API_LEVEL_24
=> Fix Typo in Tx Check screen
