- lib_nbgl/src/nbgl_use_case.c
When displaying a details view (with nbgl_useCaseViewDetails() for example), it was impossible to navigate backward if more
than 3 pages. It is now fixed
> Stax - Fixes backward navigation in details view use case

- lib_bagl/src/bagl.c
This PR remove a warning about an unused parameter, when the **#define HAVE_UNICODE_SUPPORT** is not set.
> Remove warning about unused parameter: text_encoding

- lib_bagl/src/bagl.c
- lib_nbgl/fonts/nbgl_fonts.c
- lib_ux/src/ux_layout_paging_compute.c
This PR fixes an issue in UTF-8 decoding (testing > 0xF0 instead of testing >= 0xF0 for exemple).
Bolos related ticket: https://git.donjon.ledger.fr/gitea/ledger-core/bolos-ng/issues/1749
For info, Wikipedia page about UTF-8 encoding: https://fr.wikipedia.org/wiki/UTF-8
A very convenient URL to test unicodes/utf-8 values: https://www.cogsci.ed.ac.uk/~richard/utf-8.cgi?input=80&mode=hex  
Other UTF-8 related resources:
https://www.cl.cam.ac.uk/~mgk25/ucs/ISO-10646-UTF-8.html
https://www.ietf.org/rfc/rfc3629.txt
> Fix issue with UTF-8 decoding (ticket #1749)

- include/errors.h
This PR adds the **SWO_SEC_CHK_26** error code, used in bolos-ng [PR #1764](https://git.donjon.ledger.fr/gitea/ledger-core/bolos-ng/pulls/1764)
> Add error code to handle security check (ticket #1538)

- include/os_seed.h
Change the name ONBOARDING_STATUS_START_RESTORE_SEED with ONBOARDING_STATUS_SETUP_CHOICE_RESTORE_SEED.
> Change the onboarding status name ONBOARDING_STATUS_START_RESTORE_SEED

- lib_ux_stax/ux.h
Add missing UX_WAKE_UP() support for Stax, fixes https://ledgerhq.atlassian.net/browse/FWEO-829
> Fix FWEO-829 - Add missing UX_WAKE_UP() support for Stax

- include/os_io.h
- include/syscalls.h
- src/syscalls.c
Rename touch_set_state() to os_enter_standby()/os_leave_standby()
> Rename touch_set_state() to os_enter_standby()/os_leave_standby()

- include/errors.h
- lib_nfc/include/nfc.h
- lib_nfc/src/nfc.c
Set NFC_TEXT_MAX_LEN to 215
Set NFC_INFO_MAX_LEN to 30
limit text_length and info_length to respectively NFC_TEXT_MAX_LEN-1 and NFC_INFO_MAX_LEN-1 in os_parse_ndef to take into account '\0' termination character
> Adjust NDEF buffers size

- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_obj_keyboard.c
Implements https://ledgerhq.atlassian.net/browse/FWEO-822 by using left-justified entered text in screens using Keyboard in layout API
> Stax - Entered text (with keyboard) should be left justified 

- .github/workflows/check_clang_static_analyzer.yml
- lib_bagl/src/bagl.c
- lib_nbgl/fonts/nbgl_fonts.c
- src/os_io_seproxyhal.c
Cherry-picks from https://github.com/LedgerHQ/ledger-secure-sdk/pull/201
Missing https://github.com/LedgerHQ/ledger-secure-sdk/pull/201/commits/3a9a0fc1d4c9b433c150040d8b09b37ca9fbffa1 because it doesn't apply.
But as it it only necessary for Nanos this is not an issue on this API_LEVEL branch.
- Add a workflow running Clang static anaylzer.
- Fix existing warnings and errors.
> Cherry-pick: API_LEVEL_1: Add Clang check and fix Clang issues

- lib_bagl/src/bagl.c
(cherry picked from commit 40d9bbfe43c7778bd59886f78e4b472e75ead8a5)
This was merged in https://github.com/LedgerHQ/ledger-secure-sdk/pull/176 and not cherry-picked in API_LEVEL_1 branch which needs it.
> Cherry-pick: API_LEVEL_1: Remove warning about unused parameter: text_encoding

- .github/workflows/check_clang_static_analyzer.yml
- src/os.c
- src/os_printf.c
- Update workflow running Clang static analyzer to include DEBUG=1 builds
- Fix existing warnings when building with DEBUG=1
> Fix build warnings when printf

- .github/workflows/check_clang_static_analyzer.yml
- src/os.c
- src/os_printf.c
Cherry-picks from https://github.com/LedgerHQ/ledger-secure-sdk/pull/206
Disable clang static analyzer on stax as on API_LEVEL_1 stax is named fatstacks.
> Cherry-pick: API_LEVEL_1: Fix build warnings when printf

- include/os_settings.h
- include/syscalls.h
- lib_nbgl/fonts/nbgl_fonts.c
- lib_nbgl/include/nbgl_fonts.h
- lib_nbgl/src/nbgl_draw.c
- lib_ux/include/ux.h
- lib_ux_stax/ux.h
- src/syscalls.c
Currently language packs were constantly polled by UX before being used, which is not efficient.
Instead, a notification mechanism (OS->UX) has been implemented, used by the OS everytime a Language Pack is added/moved/deleted.
In the same PR, to clarify language pack usage, the unique syscall (fetch_language_pack) has been split into 2 distinguished syscalls (fetch and get)
> Improved language pack synchronization

- lib_nbgl/doc/nbgl_api.dox
- lib_nbgl/fonts/nbgl_font_rom.inc
- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/include/nbgl_screen.h
- lib_nbgl/src/nbgl_bottom_button.c
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_navigation.c
- lib_nbgl/src/nbgl_obj_keyboard.c
- lib_nbgl/src/nbgl_obj_keypad.c
- lib_nbgl/src/nbgl_screen.c
- lib_nbgl/src/nbgl_touch.c
The goal is to move the touch callback at screen level instead of obj level, to save RAM (and flash), and because keeping it at object level is most of the time useless, as callback are most of the time already declared for a given screen.
The High-Level API of NBGL is not affected by this change.
- [ *] New feature (non-breaking change that adds functionality)
> Stax - Move touch callback at screen level instead of obj level

- include/os_io.h
- include/syscalls.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_obj_keyboard.c
- lib_nbgl/src/nbgl_screen.c
- src/syscalls.c
Add syscall to configure excluded borders for touch (to fix https://ledgerhq.atlassian.net/browse/FWEO-842)
This syscall is supposed to be called when entering pages containing keyboard to disable left border exclusion and to call it afterward to reenable it
> Add syscall to configure excluded borders for touch

- src/checks.c
checks.c: Remove unused variable slot which generates a warning at build time when `HAVE_PENDING_REVIEW_SCREEN`
> checks.c: Remove unused variable slot

- Makefile.rules_generic
Allow apps to specify prebuild target in APP_CUSTOM_TARGETS.
Previously this was done like https://github.com/LedgerHQ/app-dock/pull/17/files
> Makefile: allow app to specify prebuild target in APP_CUSTOM_PREBUILD_TARGETS

- Makefile.rules_generic
This fix a regression from 01d5cd4f9eb69ca6071736af7ebc3d832da1d8bd
> Some app use `bin/app.elf` as default makefile target instead of `default`.
> Therefore we should keep for now the `prepare` dependency on next target
> in order not to break these apps build...
> At some point, this should be changed in the apps and removed from the SDK.
> Makefile: Fix build of app that doesn't use default target

- Makefile.defines
- src/os_printf.c
Enable more build warnings and add option to enable ` -Werror`.
List inspired from app usage, discussion with other devs and https://embeddedartistry.com/blog/2017/06/07/warnings-weverything-and-the-kitchen-sink/ and https://clang.llvm.org/docs/DiagnosticsReference.html#id413
> Makefile.defines: Enable more build warnings and add option to enable  -Werror

- .github/workflows/check_clang_static_analyzer.yml
Modify workflow so that build uses `-j` and `WERROR=1`.
> workflow: Enable -j and WERROR=1 for boilerplate clang check

- Makefile.rules_generic
This reverts commit 43e346283229b9fb52725c302e5208ef0ef97431.
this is causing issue for the OS side.
> Revert "Makefile: allow app to specify prebuild target in APP_CUSTOM_TARGETS"

- Makefile.rules_generic
First revert previous try that wasn't great:
- https://github.com/LedgerHQ/ledger-secure-sdk/commit/43e346283229b9fb52725c302e5208ef0ef97431 from https://github.com/LedgerHQ/ledger-secure-sdk/pull/223
- https://github.com/LedgerHQ/ledger-secure-sdk/commit/80e3c76c01159270d58e568fad7238058a0df773 from https://github.com/LedgerHQ/ledger-secure-sdk/pull/239
Then add a better one that doesn't break the compatibility while:
- Allowing apps to add dependencies to the build step using APP_CUSTOM_BUILD_DEPENDENCIES
- Allowing apps to add dependencies to the link step using APP_CUSTOM_LINK_DEPENDENCIES
- Cleanup Makefile.rules_generic dependencies on `prepare` target and on `Makefile` 
Tested with building an app with `make -j` with having firstly added in the Makefile:
```
.PHONY: toto
toto: …
```
> Makefile: Add possibility to add BUILD and LINK dependencies

- .github/workflows/check_clang_static_analyzer.yml
- Makefile.defines
Some apps uses `WERROR` in their makefiles (caradano, fio, ...) So previous parameter name was causing issue.
Makefile: Rename WERROR param to ENABLE_SDK_WERROR
> Makefile: Rename WERROR param to ENABLE_SDK_WERROR

- include/os_io.h
- include/os_io_seproxyhal.h
- include/syscalls.h
- src/os_io_seproxyhal.c
- src/syscalls.c
Place touch read sensi syscall usage under HAVE_TOUCH_READ_SENSI_SYSCALL ifdef
Read sensi syscall was defined under HAVE_TOUCH_DEBUG ifdef, applications that were using this syscall must update their makefile with replacing HAVE_TOUCH_DEBUG with HAVE_TOUCH_READ_SENSI_SYSCALL
> Restrict touch debug related calls

- include/os_seed.h
- lib_standard_app/crypto_helpers.c
- lib_standard_app/crypto_helpers.h
- os_seed.h: Add no_throw wrappers on os_perso_derive syscalls
- lib_standard_app: Add bip32_crypto helpers
> Add crypto helpers

- include/os_seed.h
Update os_seed new API prototype merged in #261 so that they shore common type from previous function (not using `intx_t` types).
> os_seed.h: Homogenize API

- lib_nbgl/include/nbgl_types.h
- lib_nbgl/src/nbgl_obj.c
- lib_nbgl/tools/icon2glyph.py
- lib_nbgl/tools/nbgl_rle.py
- lib_ux_stax/ux.h
- App icons are now image files that can be up to 4BPP.
App icons (generated with `icon2glyph --hexbitmaponly`) are now NBGL image files, and the OS will not accept app icons that are not compliant with the image file format and dimensions.
> Fat: Adapt icon2glyph and buffers for 4BPP app icons

- lib_ux_stax/ux.h
The OS does not need this buffer to be 520 anymore.
`string_buffer` had been made bigger, in order to implement 4BPP app icons.
Optimizations on OS side allow to restore this buffer to its original size.
> Fat: Restore string buffer size

- Makefile.standard_app
- include/os_io_seproxyhal.h
Add NFC support in Makefile.standard_app
To enable NFC on a STAX app, please add the following enabler in your app Makefile
```
ENABLE_NFC = 1
```
> NFC support 

- lib_nbgl/src/nbgl_draw.c
'@' character compressed length was bigger than 255. The stored byte count on `nbgl_drawText` was on 8 bits only, making a badly rendered '@'. This variable is now an `uint16_t`.
> Fat: Fix nbgl_drawText for data larger than 255

- include/os_utils.h
- src/os.c
Backport of https://github.com/LedgerHQ/ledger-secure-sdk/pull/283
> Add a FORCE_RESET_BSS_SEGMENT API to reset the BSS segment to 0

- include/os_utils.h
- src/os.c
Backport of https://github.com/LedgerHQ/ledger-secure-sdk/pull/283
> Add a FORCE_RESET_BSS_SEGMENT API to reset the BSS segment to 0.

- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_obj.c
The goal is to enable using spinner on black background, and to play tune before screen refresh when a switch is touched.
> Improve spinner design on black background and play tune before switch refresh

- include/syscalls.h
- lib_nbgl/include/nbgl_front.h
- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/include/nbgl_side.h
- lib_nbgl/include/nbgl_types.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_obj.c
- src/syscalls.c
Add a `post_refresh` parameter to display refresh syscalls.
This parameter allows to customize power off & power on behavior after refresh.
Keeping the display powered on makes following refresh more reactive.
This PR also implement the usage of this new parameter in the nbgl objects when necessary.
```
typedef enum nbgl_post_refresh_t {
POST_REFRESH_FORCE_POWER_OFF,  ///< Force screen power off after refresh
POST_REFRESH_FORCE_POWER_ON,   ///< Force screen power on after refresh
POST_REFRESH_KEEP_POWER_STATE, ///< Keep screen power state after refresh
} nbgl_post_refresh_t;
```
`nbgl_frontRefreshArea` and `nbgl_sideRefreshArea` have a new argument.
> Fat: Post refresh power optimization

- src/os_io_seproxyhal.c
Receive status reponse before sending piezo command.
The previous implementation systematically received spi response when sending piezo command - making some seph messages being discarded (such as touch or timer)
> Fat: Receive status resp before sending piezo cmd

- include/os_lib.h
An attribute was missing, it triggered false positive warnings at compilation
> Add __attribute__((noreturn)) for os_lib_end SYSCALL

- lib_nbgl/src/nbgl_layout.c
Fix QR Code position when not centered (add vertical offset)
> Stax - Fix QR Code position when not centered (add vertical offset)

- lib_ux_stax/ux.h
- src/syscalls.c
Rename `delete_background_img` syscall argument.
> Fat: Rename delete_background_img argument

- lib_nbgl/src/nbgl_layout.c
Use 4BPP font for spinner text.
> Fat: Use 4BPP for spinner text

- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/src/nbgl_obj.c
- lib_ux_stax/ux.c
Fixes https://ledgerhq.atlassian.net/browse/FWEO-924 to forbid Apps to redraw/refresh screen when disallowed by UX
- [*] Breaking change (change that is not backwards-compatible and/or changes current functionality)
The OS must be updated to a new API-LEVEL
> Do not display in App if not allowed by UX

- Makefile.defines
Makefile.defines: Expose API_LEVEL to the app
this might be needed when app need to handle rare features that are not completely back-ported on all API_LEVELs as https://github.com/LedgerHQ/ledger-secure-sdk/pull/188.
> Makefile.defines: Expose API_LEVEL to the app

- lib_standard_app/parser.c
- unit-tests/lib_standard_app/test_apdu_parser.c
lib_standard_app/parser.c: Allow parsing APDU without Lc field
> lib_standard_app/parser.c: Allow parsing APDU without Lc field

- Makefile.standard_app
Makefile.standard_app: Format APP_FLAGS in hex.
This is the format that is often used in makefiles and in the app database, so stick with it.
> Makefile.standard_app: Format APP_FLAGS in hex

- Makefile.defines
Relates to https://ledgerhq.atlassian.net/browse/EMBSDK-18
Makefile.defines: Drop SEED_COOKIES mechanism
Remove the seed cookie mechanism on Nanos and Stax device.
> Makefile.defines: Drop SEED_COOKIES mechanism

- include/os_io_seproxyhal.h
- lib_ux/include/ux.h
- lib_ux_stax/ux.h
- src/os_io_seproxyhal.c
Add new boolean parameter "criticalBattery" to io_seproxyhal_power_off() to indicate if power off is due to critical battery condition
> Indicate if poweroff was triggered by critical battery level

- include/decorators.h
- include/os_seed.h
- lib_standard_app/crypto_helpers.c
- lib_standard_app/crypto_helpers.h
include: decorators.h: Add WARN_UNUSED_RESULT attribute decorator
os_seed.h / crypto_helpers: Use WARN_UNUSED_RESULT decorator
os_seed.h / crypto_helpers: Ensure output buffers are memset in case of error
> Sanitise some crypto functions

- Makefile.rules
Expose all headers with their full paths.
> Makefile.rules: add ${BOLOS_SDK} to INCLUDES_PATH

- include/os_io.h
- include/os_io_seproxyhal.h
- include/syscalls.h
- src/os_io_seproxyhal.c
- src/syscalls.c
Implement read touch diff data
New syscall touch_read_diff_data() syscall_id (0x01fa0010) New SDK function io_seproxyhal_touch_read_diff_data() to wrap the syscall
> Read Stax touch diff data (debug feature)

- include/errors.h
Add new error code SWO_APD_DAT_33 (0x6833)
> Add new error code

- lib_nbgl/src/nbgl_obj_keyboard.c
Do not poweroff screen for better reactivity when using the keyboard in an app
- [ X] Bugfix (non-breaking change that solves an issue)
> stax: dont poweroff display when using keyboard

- lib_nbgl/src/nbgl_use_case.c
Long appname were broken often split in the middle of the word.
> nbgl: handle long APPNAME for useCaseHome

- lib_nbgl/include/nbgl_use_case.h
- lib_nbgl/src/nbgl_use_case.c
Very long appnames resulted in a truncated string in the home screen.
This solve the issue by defining a default string in case the app fails at providing a custom string.
> nbgl: handle very long app names

- lib_bagl/src/bagl_font_open_sans_extrabold_11px.json
- lib_bagl/src/bagl_font_open_sans_light_16px.json
- lib_bagl/src/bagl_font_open_sans_regular_11px.json
Contains the .json files with font data for Nano X & Nano S+
(those files are JSON versions of the .inc files, to be able to use them with Python to fix speculos OCR troubles)
> Add API_LEVEL_5 JSON files for Nano fonts

- include/os_io.h
- include/os_io_seproxyhal.h
- include/syscalls.h
- src/os_io_seproxyhal.c
- src/syscalls.c
Syscalls with ID SYSCALL_touch_read_sensi_ID and SYSCALL_touch_read_diff_data_ID are merged into one syscall with ID SYSCALL_touch_debug_ID
A second parameter has been added to the merged syscall to allow "dispatching" the two previous syscalls
So depending on this parameter value, this new syscall can:
- fetch touch raw data
- fetch touch diff data
- set touch panel in "read coordinates mode" (used by a caller script, to setup STAX in "standard mode" (ie read coordinates) after test
Breaking API change with SDK functions renaming (touch debug functions only used by STAX touch test apps)
> STAX Touch debug data syscalls factorization

- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_obj_keyboard.c
Fine tune some alignements on Stax to match with figma screens.
Impacted alignments:
- Keyboards
- Radio buttons
- Spinner
- Pin bullets
> Fat: Fine tune alignments

- lib_standard_app/main.c
Previous behavior was to catch the Exception and somehow restart the app. This was somehow hiding the error as the user would not see the app crash. As Exception should not be raised in nominal situation or should be caught before, we changed the behavior to directly exit the app.
This also have the benefit of avoiding issue where the whole app BSS should be reset to have a sane behavior when the app was restarted.
Linked to https://github.com/LedgerHQ/app-boilerplate/pull/85
> lib_standard_app: main.c: Improvements

- src/checks.c
CIs using the guidelines_enforcer are failing on recent builds with Nano X updated to API_LEVEL_5 because of an unused variable, which was fixed on master already. (ex. https://github.com/ton-blockchain/ledger-app-ton/actions/runs/5403907636/jobs/9817380906#step:4:39)
> Fix CI failure (scan-build) on API_LEVEL_5

- Makefile.rules
- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/include/nbgl_screen.h
- lib_nbgl/serialization/Makefile
- lib_nbgl/src/nbgl_bottom_button.c
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_navigation.c
- lib_nbgl/src/nbgl_obj.c
- lib_nbgl/src/nbgl_obj_keyboard.c
- lib_nbgl/src/nbgl_obj_keypad.c
- lib_nbgl/src/nbgl_screen.c
- lib_nbgl/src/nbgl_touch.c
The goal is to get rid of anonymous structure used as members of other structures in NBGL objects, to simulate inheritance.
This mechanism is not full C-compatible.
The chosen solution is to name this sub-structure.
Note: -fms-extensions and -Wno-microsoft-anon-tag build options can then be removed.
- [*] Breaking change (change that is not backwards-compatible and/or changes current functionality)
Some objet fields need to be addressed by this field names now
> Do not use anonymous struct anymore

- include/os_seed.h
`scan-build -enable-checker alpha.unix.cstring.OutOfBounds` showed a few `explicit_bzeroes` were clearing the pointer (and part of the stack...) instead of the intended array.
These were in a `CATCH` clause so could not be seen on the happy path.
> fix: improper use of bzero

- lib_nbgl/src/nbgl_obj_keyboard.c
- lib_nbgl/src/nbgl_touch.c
- src/os_io_seproxyhal.c
Fixes:
- https://ledgerhq.atlassian.net/browse/FWEO-950 : by returning 0x5515 error code to any APDU in “locked” state as soon as PIN is set, instead of as soon as device is onboarded.
- https://ledgerhq.atlassian.net/browse/FWEO-954 : by better handling of the touched objet limits and protection in letter-only mode
> Fix unexpected behaviors in stax UI

- lib_nbgl/src/nbgl_use_case.c
When calling `nbgl_useCaseRegularReview` and setting a `TAG_VALUE_LIST`, the first screen appears as intented (with the full value displayed ), yet when going backwards the values appeared cropped with "...".
This happened because the `tagValueList.nbMaxLinesForValue` had a value of 1 instead of 0 the second time, due to the structure not being initialized.
The NBGL should initialize the structure.
> fix undefined behaviour

- include/errors.h
- include/seproxyhal_protocol.h
Add error codes and seph tags relative to Stax Qi reflashing feature.
No breaking changes - but these codes won't work without the latest OS and MCU version.
> Fat: Implement Qi reflashing

- src/os_io_seproxyhal.c
Folliwing fix of FWEO-950, a regression has been introduced, making Apps use the os_perso_is_pin_set() syscall, not available except for UX
> Ensure no os perso is pin set in apps

- Makefile.standard_app
Allow app to define only the URL in its makefile
> standard_app: allow URL to be defined in app makefile

- include/syscalls.h
- lib_nbgl/include/nbgl_screen.h
- src/syscalls.c
Add two syscalls to reduce risks of Stax display bleeding.
> Fat: Add anti-bleeding syscalls

- include/os_pin.h
- src/os_io_seproxyhal.c
Make os_perso_is_pin_set available to regular applications when processing default apdu.
Change the syscall's privilege.
> Enable os_perso_is_pin_set for non-privileged applications

- Makefile.glyphs
Replace info with warn for deprecated Makefile flags
> Replace info with warn for deprecated Makefile flags

- include/syscalls.h
- src/syscalls.c
Delete `os_ux_result` syscall.
From @apaillier-ledger tests, no official app is impacted by this change.
The `os_ux_result` syscall is not available anymore.
> Delete `os_ux_result` syscall

- lib_standard_app/debug.c
- lib_standard_app/debug.h
- lib_standard_app/main.c
- src/os.c
- os: Compute usable THROW LR value and allow app to access it
- lib_standard_app: Add a mecanism to display a debug screen upon Throw reception
> Add helper to allow easier debugging of Throw

- Makefile.standard_app
Spaces would not be handled properly in the CFLAGS given to the compiler when added with `DEFINES`, it would be visibly wrong when seen on the Stax app home screen.
> Fix APPNAME handling in standard app Makefile

- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_use_case.c
Use word-wrapping by default for almost all text areas in NBGL layout
Related to https://ledgerhq.atlassian.net/browse/FWEO-973
> Use word-wrapping by default for almost all text areas in NBGL layout

- include/os_endorsement.h
- include/syscalls.h
- src/syscalls.c
This PR includes modifications needed by the OS for the new endorsements feature
This PR removes precompiler macros, thus activating by default features that were not activated on previous OS releases => breaking change
> Endorsement display

- lib_nbgl/src/nbgl_obj_keyboard.c
The goal is to be able to hide/disable backspace in keyboard when disabled in keyMask
> Mask backspace in keyboard when disabled in keyMask

- include/os_apilevel.h
- include/os_id.h
- src/os_io_seproxyhal.c
Deprecate `check_api_level` function
> Deprecate "check_api_level" function

- lib_cxng/include/lcx_ecdsa.h
Deprecate `cx_ecdsa_verify`, as `cx_ecdsa_verify_no_throw` exists
> Deprecate cx_ecdsa_verify

- lib_cxng/include/lcx_ecdsa.h
- lib_standard_app/crypto_helpers.c
- lib_standard_app/crypto_helpers.h
- src/cx_wrappers.c
cx_wrappers: Implement cx_ecdsa_sign_rs_no_throw
lib_standard_app: crypto_helpers: Implement bip32_derive_ecdsa_sign_rs_hash_256
See https://ledgerhq.atlassian.net/browse/B2CA-1386
> CX: Add helper to retrieve ECDSA signature R and S values

- lib_stusb_impl/usbd_impl.c
> [fix] Unused arguments in lib_stusb_impl/usbd_impl.c:USBD_HID_DataOut_impl when HAVE_USB_HIDKBD macro is set

- lib_nbgl/tools/icon2glyph.py
- lib_nbgl/tools/nbgl_rle.py
icon2glyph.py crashed when encountering a 2BPP image
> Fix icon2glyph script

- README.md
README.md: Update API_LEVEL branches
> README.md: Update API_LEVEL branches

- include/os_time.h
- include/syscalls.h
- src/syscalls.c
Add `os_set_ux_time_ms` syscall dedicated to the UX app.
The goal is to share time to the OS layer, in order to implement actions based on time.
> Add UX specific syscall to share time with OS

- include/os_screen.h
- include/os_types.h
- lib_bagl/include/bagl.h
- lib_bagl/src/bagl.c
- src/syscalls.c
Update syscall signature to return an error instead of throwing.
> Make bagl_hal_draw_bitmap_within_rect to return errors instead of throwing

- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_use_case.c
lib_nbgl: Constify nbgl_layoutTagValueList_t pairs element
this allow to use const pairs, and therefore pairs from flash without having to drop the `const` qualifier.
> lib_nbgl: Constify nbgl_layoutTagValueList_t pairs element

- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/src/nbgl_layout.c
The goal is to support long press button in screenshots generation
> Support long press button in screenshots generation

- Makefile.rules_generic
- target/nanos/script.ld
- target/nanos2/script.ld
- target/nanox/script.ld
- target/stax/script.ld
script.ld/Makefile: Use the maximum ram size available for the stack
APP_STACK_SIZE is now ignored, and replaced by APP_STACK_MIN_SIZE.
> script.ld/Makefile: Use the maximum ram size available for the stack

- src/os_io_seproxyhal.c
The goal is to be able to serialize bigger NBGL objects for Stax/Nano Testing
> Increase NBGL serialization buffer size to 200 bytes

- target/stax/script.ld
Fix stax Linker script SRAM length value
> stax: script.ld: Fix SRAM length

- lib_cxng/include/lcx_cipher.h
Remove const qualifier for a CX field - in the context of an OS upgrade app.
> Fix CX warning in OS update context

- src/os_io_seproxyhal.c
> Fix static analysis issue

- include/os_io_seproxyhal.h
- src/os_io_seproxyhal.c
`io_seproxyhal_enable_io()` and `io_seproxyhal_disable_io()` allow to turn on and off USB connection.
Add a function needed by BOLOS.
> Add `io_seproxyhal_enable_io()` function

- include/os_settings.h
Depending on the target or the on compiler version used, osu build can fail on an implicit declaration of `os_setting_update()`. That's because this function is declared behind `HAVE_LANGUAGE_PACK` flag.
This PR moves the function declaration to fix this issue
- [ *] Bugfix (non-breaking change that solves an issue)
> FIX osu build - always declare function os_setting_update()

- lib_nbgl/include/nbgl_screen.h
- src/syscalls.c
- unit-tests/lib_nbgl/test_nbgl_obj.c
- unit-tests/lib_nbgl/test_nbgl_screen.c
Update a NBGL syscall signature that generates a warning in the OSU.
The implementation of this syscall do not return anything so update the signature.
> NBGL: fix syscall signature that generates a warning in the OSU

- lib_cxng/src/cx_aes.c
Fix some warnings needed for OSU build
> cx aes: fix some warnings for the OSU

- lib_cxng/src/cx_aes.c
Fix cx UTs but keep code warning free for the OSU.
- [X ] Other (for changes that might not fit in any category)
> CX: Fix UTs and keep OSU warning free

- lib_ux/include/ux.h
On devices where the SE drives the screen, there is no need for seph exchanges to control the screen.
The previous version was assuming UX_DISPLAY_NEXT_ELEMENT() was changing the state of the MCU <-> SE exchanges, which is false, this was leading to a deadlock on Speculos.
> lib_ux/include/ux.h: Fix LNX and LNSP version of UX_WAIT_DISPLAYED()

- lib_nbgl/src/nbgl_fonts.c
The goal of this PR is to fix nbgl_getTextMaxLenInNbLines() computing wrong len for non wrappable text
> Fix nbgl_getTextMaxLenInNbLines() computing wrong len for non wrappable text

- lib_nbgl/include/nbgl_use_case.h
- lib_nbgl/src/nbgl_use_case.c
[Please provide a detailed description of what was done in this PR.
(And mention any links to an issue [docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))](nbgl: Add nbgl_useCaseForwardOnlyReviewNoSkip())
> nbgl: Add nbgl_useCaseForwardOnlyReviewNoSkip()

- src/os_printf.c
Brings it more in line with other API levels. Required for plugins compilation with all their disablers.
> Remove unnecessary includes in os_printf

- lib_nbgl/src/nbgl_use_case.c
Ensure state properly reset when entering `ForwardOnlyReview`, `AddressConfirmation` use cases.
Fixes https://github.com/trilitech/ledger-app-tezos-wallet/issues/63
When displaying `AddressConfirmation` page, if a `useCaseReview` was rejected previously, the `Continue` button is partially overriden with a `Tap to Continue` text.
When using `ForwardOnlyReview`, if the user previously entered `Settings`, where settings has more than one page, then during the review, the `BackButton` is visible, despite `ForwardOnlyReview` being used.
- Set the `nextPageText` to `NULL` when entering `AddressConfirmation`
- Explicitly set the backButton to `false` when entering `ForwardOnlyReview*` use cases.
Please post …
> nbgl: ensure state set to correct values in certain `use_case` flows

- include/os_ux.h
- src/os_io_seproxyhal.c
Introduces usage of BOLOS_UX_IO_RESET event for apps: 
Warns the UX layer that an IO reset will happen. 
It allows UX layer to anticipate jitter in USB values and avoid undesired pin locks.
The addition of this new event shifts the values of multiple UX event values.
> Avoid unwanted pin lock during io reset

- Makefile.rules
- Makefile.rules_generic
Avoid object files conflict when building an APP:
- Separate object files into 2 distinct directories for both SDK and APP
- Same modification for dependency files
- Warn if same headers filename are found in both SDK and APP
- Simplify the way source files list is generated
:heavy_check_mark: Tested and validated with `bolos-ng`.
Jira ticket: https://ledgerhq.atlassian.net/browse/B2CA-1408
This also fixes a dependency issue on `nanos`, where make always rebuilds everything.
- `app-algorand`:
- Multiple definition for the function `base64_encode` in both App and  `zxlib` dependency.
- https://github.com/LedgerHQ/app-algorand/pull/44
- `app-ardor`:
- c file dynamially generated, with hardcoded `obj/` path. An external PR is currently under security review before being merged soon. It is …
> BC2A-1408: Fix conflict name issue during APP building

- .github/workflows/force-rebase.yml
Add a workflow to enforce a rebase before merge to ensure keeping a semi-linear history which allows to easily understand the commits change order and ensure easy cherry-picks.
> CI: Add workflow to enforce rebase before merge

- include/ledger_assert.h
Add `os.h` include when using `HAVE_PRINTF` for ledger_assert
> ledger_assert: add header for HAVE_PRINTF

- lib_stusb/STM32_USB_Device_Library/Class/CCID/inc/sc_itf.h
- lib_stusb/STM32_USB_Device_Library/Class/CCID/inc/usbd_ccid_if.h
- lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_cmd.c
- lib_stusb/STM32_USB_Device_Library/Class/CCID/src/usbd_ccid_if.c
- lib_stusb/usbd_conf.h
- lib_stusb_impl/usbd_impl.c
This PR
- Adds a pinpad activation, allowing to set the password (usefull for Apps like OpenPGP).
- Fixes the `SC_Secure` function because the data parsing was not aligned with CCID spec, and the returned payload caused the app crashing
- In addition, few fix for compilation warnings about code formatting.
> B2CA-969: Activate pinpad and fix CCID SC_Secure

- lib_cxng/src/cx_cmac.c
Reset cipher module at the end of CMAC calculation.
> Reset cipher module at the end of cmac

- include/cx_errors.h
- include/ledger_assert.h
- include/ledger_assert_internals.h
- include/os.h
- include/os_print.h
- lib_cxng/include/lcx_ecdsa.h
- lib_cxng/include/lcx_ecschnorr.h
- lib_cxng/include/lcx_eddsa.h
- lib_cxng/include/lcx_groestl.h
- lib_cxng/include/lcx_hash.h
- src/ledger_assert.c
Add some documentation for `LEDGER_ASSERT`
Allow `printf` like usage of `LEDGER_ASSERT` for error message
Minor cleanup on CX includes
Add `CX_ASSERT` macro
> LEDGER_ASSERT improvments and CX_ASSERT addition

- lib_nbgl/src/nbgl_use_case.c
Just fix the compilation warning 
```
[CC]   build/stax/obj/nbgl_use_case.o
/work/apps/B2CA-969/stax-secure-sdk//lib_nbgl/src/nbgl_use_case.c:782:14: warning: variable 'currentHeight' set but not used [-Wunused-but-set-variable]
uint16_t currentHeight = 0;
^
1 warning generated.
```
Also fix `clang-format` for the variable definitions in the same function.
> Remove currentHeight unused var in nbgl_use_case

- lib_nbgl/src/nbgl_obj.c
The goal is to factorize serialization of NBGL refresh, to send the "REFRESH" info to TTYT even when doing full (Side+Front) refresh in Stax
> Factorize serialization of NBGL refresh

- lib_nbgl/src/nbgl_use_case.c
nbgl_use_case.c: Fix unitialized variable passed as a callback
We might consider that it's the callback responsability to init it, but as it's not what is done in displayReviewPage() and it is safer for a small cost, let's do it!
> nbgl_use_case.c: Fix unitialized variable passed as a callback

- lib_nbgl/src/nbgl_layout.c
Pinpad is designed by defaut to support up to 8 digits.
For OpenPGP, we must support up to 12 digits.
This PR reduces the space between bullets for long pin code (more then 8), and returns an error if the nb of digits is too long.
> Update bullet space for 12-digit pin code

- Makefile.standard_app
- include/os_io.h
- lib_standard_app/io.c
- src/os_io_seproxyhal.c
os_io_seproxyhal: Introduce new IO_RECEIVE_DATA flag for io_exchange()
lib_standard_app/io.c: Send RAPDU immediately and use IO_CONTINUE_RX flag
> IO Continue RX flag and sync RAPDU sending

- include/os_io.h
- include/os_io_seproxyhal.h
- include/syscalls.h
- src/os_io_seproxyhal.c
- src/syscalls.c
Add one parameter to touch_switch_debug_mode_and_read syscall, to allow reading offset data on europa touch
Write new method io_seproxyhal_touch_debug_read_offset_data for europa
New syscall parameter, new syscall ID
> Pbo europa touch read sensor buffer

- src/os_io_seproxyhal.c
This PR is needed to allow BOLOS to activate NFC by default on STAX, non-breaking change
> Activate NFC by default

- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/include/nbgl_step.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_step.c
The goal of this PR is to fix some build issues of Bolos, on Nano targets using NBGL.
This is mainly due to missing renaming of some structures
> Fix build issues with Bolos with Nano targets on NBGL

- lib_cxng/include/lcx_blake2.h
- lib_cxng/include/lcx_common.h
- lib_cxng/include/lcx_ripemd160.h
- lib_cxng/include/lcx_sha256.h
- lib_cxng/include/lcx_sha3.h
- lib_cxng/include/lcx_sha512.h
- src/cx_hash_iovec.c
lib_cxng: Introduce helpers for one-shot hashs
Tested on Speculos and on device (NanoS and NanoX) with the following app-boilerplate patch:
[patch.txt](https://github.com/LedgerHQ/ledger-secure-sdk/files/14344832/patch.txt)
> lib_cxng: Introduce helpers for one-shot hashs

- lib_cxng/include/lcx_sha256.h
Fix build issue when HAVE_SHA256 is defined but not HAVE_SHA224.
> Extend #ifdef HAVE_SHA224

- Makefile.standard_app
Add TARGET_EUROPA in makefile.standard_app for NFC support
Remove lib_nfc/ from SDK_SOURCE_PATH (Only used by the OS)
> Fix NFC support on Europa

- lib_nbgl/include/nbgl_obj.h
lib_nbgl: Fix missing backward compatibility icons
lib_nbgl: Add deprecation warning on backard compatiblity icons alias
> Nbgl fix missing glyphs

- lib_nbgl/src/nbgl_touch.c
The goal of this PR is to handle swipe gesture detection (by polling) in the case of screens without swipeable objects.
In this case, the event shall not be seen as a swipe but as a regular touch release.
> Handle swipe on screens without swipeable objects

- Makefile.standard_app
This PR fixes a typo in Makefile.standard_app that lead to NFC not beeing complied even if ENABLE_NFC=1 was present in app Makefile
> Fix typo in Makefile.standard_app for NFC activation

- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_layout_internal.h
- lib_nbgl/src/nbgl_layout_internal_nanos.h
- lib_nbgl/src/nbgl_layout_keyboard.c
- lib_nbgl/src/nbgl_layout_keyboard_nanos.c
- lib_nbgl/src/nbgl_layout_keypad.c
- lib_nbgl/src/nbgl_layout_keypad_nanos.c
- lib_nbgl/src/nbgl_layout_nanos.c
- lib_nbgl/src/nbgl_layout_navigation.c
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to split  NBGL layout layer implementation, because it's getting to big to fit a single file.
The implementation for Nano and Wallet have to be split, and then the implementations of Keyboard, Keypad and Navigation bar.
> Split NBGL layout layer

- lib_nbgl/src/nbgl_use_case.c
Fix Europa nbgl use_case: remove "Skip" button in confirmation page
> Europa nbgl use case: No "Skip" bttn at sign page

- lib_nbgl/include/nbgl_types.h
INIT_REFRESH is used by OS to fully clear the screen in white.
> Add INIT_REFRESH in nbgl_refresh_mode_t

- Makefile.app_params
Makefile.app_params: Keep only last appFlags value
This is fixing issues where app set multiples value for Nanox, and only the last one was used by LedgerBlue loadApp script, but the new Makefile.app_params was generating invalid parameter in such cases.
> Makefile.app_params: Keep only last appFlags value

- lib_nbgl/src/nbgl_layout_keyboard.c
Make keyboards match with figma screens.
> Europa: Fix keyboard layout

- lib_nbgl/serialization/nbgl_lib.py
- lib_nbgl/src/nbgl_obj_keyboard.c
(cherry picked from commit 9fd7b8d721461c4be230a21db30b31a180c70ee8)
> Fix FWEO-1047 - Inverted shift and caps lock icons

- include/os_io_seproxyhal.h
- src/os_io_seproxyhal.c
Add new define NFC_APDU_MAX_SIZE (256), and check it against tx_len before sending nfc rAPDU.
This modification allows the OS to catch an nfc rAPDU overflow, before forwarding the rAPDU to the MCU
> Check nfc rAPDU against maximum NFC apdu size the MCU can handle

- lib_nbgl/src/nbgl_use_case.c
lib_nbgl: nbgl_use_case.c: Fix nbgl_useCaseStaticReview handling of empty tag value list
> lib_nbgl: nbgl_use_case.c: Fix nbgl_useCaseStaticReview handling of empty tag value list

- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/src/nbgl_fonts.c
- lib_nbgl/src/nbgl_obj_keyboard.c
- lib_nbgl/src/nbgl_obj_keypad.c
The goal of this PR is to fix https://ledgerhq.atlassian.net/browse/FWEO-1056 & https://ledgerhq.atlassian.net/browse/FWEO-1059, by improving key masking on keyboard, and using a full color refresh when switching from letters to digits.
> Fix keyboard issues on stax

- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/src/nbgl_fonts.c
- lib_nbgl/src/nbgl_obj_keyboard.c
- lib_nbgl/src/nbgl_obj_keypad.c
The goal of this PR is to fix https://ledgerhq.atlassian.net/browse/FWEO-1056 & https://ledgerhq.atlassian.net/browse/FWEO-1059, by improving key masking on keyboard, and using a full color refresh when switching from letters to digits.
> Fix keyboard issues on stax api 15

- include/os_io.h
- lib_nbgl/include/nbgl_types.h
Declare nbgl_hardwareSwipe_t even if `HAVE_HW_TOUCH_SWIPE` is not defined. This type is needed for production testing, even if hardware swipe is not used in SDK.
> Europa: Always declare nbgl_hardwareSwipe_t

- lib_nbgl/src/nbgl_use_case.c
onModalConfirm was not checked in nbgl_use_case, leading to potential crashes
> NBGL: Check onModalConfirm != NULL before call

- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/src/nbgl_layout_keyboard.c
- lib_nbgl/src/nbgl_layout_keypad.c
- lib_nbgl/src/nbgl_obj.c
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to simplify the management of screens containing keyboard or keypad.
These screen also often contain a title, some control to display entered text or digits, and some controls to validate or interact. All these controls have currently to be added one by one, and their vertical aligment is tricky.
The idea of this PR is to add the concepts of keypad content and keyboard content to handle all these control as a single area (like in Figma).
The old API is kept but depracated
> Add concept of Keyboard & Keypad contents to solve alignment issues in some screens

- lib_nbgl/src/nbgl_obj_keyboard.c
- lib_nbgl/src/nbgl_screen.c
The goal of this PR is to fix a bad behavior of NBGL screen management.
Indeed, when a modal screen is "popped", the screen counter is decremented, but when there is no screen occuping the background (screen level 0), and no other modal, the counter should be reset to 0.
> Fix wrong behaviour when popping a NBGL screen when no background remaining

- Makefile.standard_app
Makefile.standard_app: Require specific app icon for Flex device
> Makefile.standard_app: Require specific app icon for Flex device

- lib_nbgl/include/nbgl_draw.h
- lib_nbgl/include/nbgl_types.h
- lib_nbgl/src/nbgl_draw.c
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_obj.c
The goal of this PR is to fix https://ledgerhq.atlassian.net/browse/FWEO-1094, by automatically detecting that a QR Code (+description) is not fitting in the screen, and use a smaller size (132x132 instead of 264x264)
> Fix FWEO-1094 - Use small QRCode when needed

- lib_stusb_impl/usbd_impl.c
USB descriptor was Europa.
Correct it to Flex.
> Flex: Update USB descriptor

- Makefile.rules
- lib_standard_app/io.c
- lib_ux_sync/include/ux_sync.h
- lib_ux_sync/src/ux_sync.c
lib_ux_sync: First version
Can be tested on API_LEVEL_15 (Stax 1.4.0-rc3 on this branch: https://github.com/LedgerHQ/ledger-secure-sdk/tree/xch/test-nbgl-sync-api-level-15
Example of usage on app-boilerplate can be seen here: https://github.com/LedgerHQ/app-boilerplate/pull/120
> lib_ux_sync: First version

- include/cx_stubs.h
- lib_cxng/cx.export
- lib_cxng/include/lcx_eddsa.h
- lib_cxng/src/cx_eddsa.c
- lib_cxng/src/cx_exported_functions.c
- src/cx_stubs.S
This PR makes functions available to separate the edDSA message hash from the signature/verification functions. This way, if the message to hash is long, it can be hashed block by block.
> Rework EdDSA functions

- lib_nbgl/fonts/config-Inter-Medium36-1bpp.ini
- lib_nbgl/fonts/config-Inter-Medium36.ini
- lib_nbgl/fonts/config-Inter-Regular28-1bpp.ini
- lib_nbgl/fonts/config-Inter-Regular28.ini
- lib_nbgl/fonts/config-Inter-SemiBold28-1bpp.ini
- lib_nbgl/fonts/config-Inter-SemiBold28.ini
- tools/ttf2inc.py
The goal of this PR is to fix https://ledgerhq.atlassian.net/browse/FWEO-1116
Thanks to a new settings in Flex font ini files, an offset is applied on each generated unicode char (the ASCII ones are not concerned because they are taken from .png files)
> Fix FWEO-1116 - Unicode chars not aligned on Flex

- lib_nbgl/src/nbgl_page.c
The goal of this PR is to fix a crash when using tag/value getter callback and TAG_VALUE_DETAILS.
In any case, when using TAG_VALUE_DETAILS, it's not necessary to recompute the number of lines, which has been computed in Use Case layer.
> Fix crash when using tag/value getter callback and TAG_VALUE_DETAILS

- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/include/nbgl_page.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_layout_internal.h
- lib_nbgl/src/nbgl_layout_navigation.c
- lib_nbgl/src/nbgl_obj.c
- lib_nbgl/src/nbgl_page.c
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to fix https://ledgerhq.atlassian.net/browse/FWEO-1133 by a better analysis of when to draw the back navigation key.
Moreover, in transactions this back navigation key shall be placed at the same place, when we display the page number or not.
> Fix FWEO-1133 - APP SDK - Streamed transactions shouldn't have a back arrow navigation

- include/os_print.h
- lib_nbgl/include/nbgl_content.h
- lib_nbgl/include/nbgl_flow.h
- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/include/nbgl_step.h
- lib_nbgl/src/nbgl_flow.c
- lib_nbgl/src/nbgl_fonts.c
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_layout_keypad_nanos.c
- lib_nbgl/src/nbgl_layout_nanos.c
- lib_nbgl/src/nbgl_obj.c
- lib_nbgl/src/nbgl_step.c
- lib_nbgl/src/nbgl_use_case_nanos.c
This PR is related to screenshots generation.
It allows you to use the constraints indicated in the JSON files containing all the strings, in order to check that the strings respect these constraints, in each supported language.
(LNX & LNS+ devices only, for the moment)
> Check strings

- lib_nbgl/src/nbgl_layout.c
https://ledgerhq.atlassian.net/browse/FWEO-1128
When fast mode is enabled, first "hold to approve" segments were displayed almost at the same time. One at touch, the other on the next ticker event.
This commit remove the first segment that is displayed at touch.
> Flex: Fix HTA double segment issue

- Makefile.defines
- Makefile.standard_app
- Makefile.target
Makefiles: Extract Makefile.target from Makefile.defines
This allow to include `Makefile.target` at the top of your app `Makefile`, then to define some app configuration that can depends on the target and eventually include the `Makefile.standard_app` which deals with including `Makefile.defines`.
> Makefiles: Extract Makefile.target from Makefile.defines

- include/cx_errors.h
Add `PRINTF` inside `CX_CHECK` to ease debug, and find the file/line of the error
> Improve CX_CHECK

- Makefile.defines
- Makefile.target
Makefiles: Fix API_LEVEL location
Some scripts expect it to be in Makefile.defines and we don't need it in Makefile.target. So keep it in the first place.
Fix a pseudo regression introduced by https://github.com/LedgerHQ/ledger-secure-sdk/pull/637
> Makefiles: Fix API_LEVEL location

- .github/workflows/build_all_apps.yml
- .github/workflows/check_clang_static_analyzer.yml
CI: Drop nanos tests
There won't be any new Os release of LNS that would use the master SDK branch.
Hence there is no reason to keep it fully supported and tested on all apps.
We should rather tests the app build using the LNS SDK branch
> CI: Drop nanos tests

- lib_nbgl/include/nbgl_content.h
- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/include/nbgl_step.h
- lib_nbgl/src/nbgl_flow.c
- lib_nbgl/src/nbgl_fonts.c
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_layout_keypad_nanos.c
- lib_nbgl/src/nbgl_layout_nanos.c
- lib_nbgl/src/nbgl_obj.c
- lib_nbgl/src/nbgl_step.c
- lib_nbgl/src/nbgl_use_case_nanos.c
The goal of this PR is to clean-up unused string id propagation when generating screenshots.
The string ids are now directly retrieved from the strings.
- [*] Other (for changes that might not fit in any category)
> Clean-up unused string ids propagation for screenshots generation

- lib_nbgl/src/nbgl_use_case.c
Update the maximum number of infos for Flex in order to fit in one screen (max 2 instead of 3)
Flex device only.
> Update the maximum number of infos for Flex

- lib_nbgl/include/nbgl_fonts.h
- lib_nbgl/src/nbgl_fonts.c
- lib_nbgl/src/nbgl_obj.c
- lib_nbgl/src/nbgl_use_case.c
- unit-tests/lib_nbgl/test_nbgl_fonts.c
The goal of this PR is to fix https://ledgerhq.atlassian.net/browse/FWEO-1175, by using a reduced version of the address displayed under the QR Code, on 3 lines
> Fix FWEO-1175 - QR code template must be aligned with design with truncated addresses

- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/src/nbgl_layout.c
In order to support some screens in Figma for Clear signing on Stax, it is useful to enable, in NBGL layout layer, to use a touchable icon in top-right position in the screen, in the header.
> Enable using a top-right icon in progress & back header

- include/cx_stubs.h
- lib_cxng/cx.export
- lib_cxng/include/lcx_aes_siv.h
- lib_cxng/src/cx_aes_siv.c
- lib_cxng/src/cx_exported_functions.c
- src/cx_stubs.S
This PR allows to update the AES-CMAC context with a block of the plaintext for AES-SIV encryption/decryption.
> Add a function to add input data to AES-CMAC

- lib_nbgl/include/nbgl_flow.h
- lib_nbgl/src/nbgl_fonts.c
- lib_nbgl/src/nbgl_layout_nanos.c
- lib_nbgl/src/nbgl_obj.c
- lib_nbgl/src/nbgl_step.c
The goal of this PR is to fix the computed number of lines for Nano, in some cases with '\f', for screenshots generation.
And also some cosmetic fixes
> Small fix in nulber of lines computed for Nano, in some cases with '\f'

- src/checks.c
- src/ledger_assert.c
Some `#define` has been deprecated, but they are still used in the code, leading to compilation warnings (already on `API_LEVEL_19`).
> [clean] Replace deprecated #defines with their replacements

- include/ox_aes.h
- lib_cxng/include/lcx_cipher.h
Use types that are arch-independent to avoid 32/64 bit portability issues.
Some unit-tests running on x86 64-bit with sanitizers enabled fails.
> Fix aes cipher portability issue

- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to properly handle value details in NBGL Use Case for Flex
Indeed, the "More" button currently opens a page without "Closing" capability, if only one page of details
> Properly handle value details in NBGL Use Case for Flex

- lib_nbgl/include/nbgl_page.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_layout_internal.h
- lib_nbgl/src/nbgl_layout_keyboard.c
- lib_nbgl/src/nbgl_layout_keypad.c
- lib_nbgl/src/nbgl_page.c
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to enable bling warning indication for reviews, to warn user in some cases.
A warning button is displayed on top-right of the first and last pages of the review, and when touched a modal warning text is displayed.
It can be activated by adding `| BLIND OPERATION` to operationType param of review.  
It enables for example the modal screen presented in https://ledgerhq.atlassian.net/browse/B2CA-1667
> Enable bling warning indication for reviews, to warn user in some cases.

- lib_nbgl/src/nbgl_layout.c
Enable Swipe on Stax, on navigation flows.
> Stax: Enable swipe in navigation flow

- lib_nbgl/src/nbgl_fonts.c
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_obj.c
- lib_nbgl/src/nbgl_step.c
This PR use textArea to check if strings are displayed outside allowed area
> Use textArea to check if strings are displayed outside allowed area

- lib_nbgl/src/nbgl_fonts.c
Fix the way nb_lines is computed on Nano devices when multiple pages are displayed.
> Fix nb_lines computation when multiple pages on nanos

- lib_stusb_impl/usbd_impl.c
Official Flex product name is Ledger Flex.
Fix USB descriptor.
> Update Flex USB descriptor

- lib_nbgl/src/nbgl_layout.c
The goal of this PR is to fix a regression that made "tap to continue" displayed in bold font instead of regular one.
> Fix "tap to continue" in bold

- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_layout_keyboard.c
- lib_nbgl/src/nbgl_layout_keypad.c
- lib_nbgl/src/nbgl_layout_navigation.c
- lib_nbgl/src/nbgl_page.c
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to align keypad and keyboard pages design on Figma specifications on Stax & Flex.
It also includes a new layout function to display some tests just under the header in some OS pages
> Align keypad keyboard screens

- lib_nbgl/include/nbgl_content.h
- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to add a new "content center" layout object to better match Figma, with a new function to create it: 
nbgl_layoutAddContentCenter().
In future commits, this function is supposed to replace nbgl_layoutAddCenteredInfo(), the goal being to have an object that exactly matches the spec on Figma.
> Add a new "content center" layout object to better match Figma

- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to force reject text to "Reject" when using old Use Case API (`nbgl_useCaseStaticReview()`, `nbgl_useCaseRegularReview()`...)
> Force reject text when using old Use Case API

- lib_ux_sync/include/ux_sync.h
- lib_ux_sync/src/ux_sync.c
Add setters for `g_ended` and `g_ret` static variables in ux sync library.
- [x ] New feature (non-breaking change that adds functionality)
> Ux sync public callbacks

- include/os_pki.h
- include/sdk_apdu_commands.h
> Update PKI command documentation and minor changes

- src/os_io_seproxyhal.c
- The `BOLOS_UX_IO_RESET` allows to avoid unwanted PIN lock when USB layer is reinited
- A defect in the OS make the very first `os_ux` message ignored
Re-send the message allows to ensure the BOLOS_UX_IO_RESET message is received by the UX layer.
> Fix BOLOS_UX_IO_RESET message when app boots

- lib_nbgl/src/nbgl_obj_keyboard_nanos.c
This PR aims to make the alphabet letter bold again during the onboarding stages of nanos.
[(And mention any links to an issue [docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue))
](https://ledgerhq.atlassian.net/browse/FWEO-1214)
> FWEO-1214 make alphabet letters bold again lnsp lnx

- lib_nbgl/src/nbgl_obj.c
The goal of this PR is to fix wrong bpp value set when drawing radio buttons. It was forced to 1BPP but radio buttons can be 1, 2 or 4 BPP
> Fix wrong bpp value when drawing radio buttons

- lib_stusb_impl/usbd_impl.c
Don't re-configure u2f endpoints every time the host sends a GetDescriptor
FIDO over USB crashes on android because Android makes GetDescriptor requests between authenticator operations. 
This PR fixes that issue by removing the old hacky code that was present in the `GetReportDescriptor_impl` function.
> Fido: Remove old usb hack

- lib_stusb_impl/usbd_impl.c
Don't re-configure u2f endpoints every time the host sends a GetDescriptor
(cherry picked from commit c49427fe2abe36667d81b2c8996dfe1961128ffa)
Next tag on API_LEVEL_5 will be: `v5.13.1`
> Remove old usb hack

- lib_stusb_impl/usbd_impl.c
This PR aims to fix the VID switching when applications are started. The VID differ from dashboard and running app.
(And mention any links to an issue [docs](https://ledgerhq.atlassian.net/browse/FWEO-1215))
> Fweo 1215 removed app product id switching

- lib_nbgl/include/nbgl_layout.h
6 suggestion buttons did not allow to select specific words from BIP39
(cherry picked from commit 341e79c5c31516219aaf9324c2156958c99bf76d)
> Flex: Fix number of suggestion buttons

- lib_nbgl/src/nbgl_use_case.c
Several fixes regarding blind signing warning icon.
> nbgl_use_case: fix useCaseStaticReview

- lib_nbgl/src/nbgl_use_case.c
- lib_ux_sync/include/ux_sync.h
- lib_ux_sync/src/ux_sync.c
cherry picks:
- [nbgl_use_case: fix useCaseStaticReview](https://github.com/LedgerHQ/ledger-secure-sdk/commit/0742a013aefde219783c27ca7fdefc071cea52ad) 
Set operationType flag in useCaseStaticReview - in order to avoid any unwanted blind signing warnings.
- [nbgl_use_case: Fix blind sign warning icon](https://github.com/LedgerHQ/ledger-secure-sdk/commit/761e45a6f73aaab9c4054f9773e3baa081e73c55) 
Blind sign warning icon was always displayed during streaming review.
Only display icon in first and last review page.
- [lib_ux_sync : add choice use case.](https://github.com/LedgerHQ/ledger-secure-sdk/pull/741/commits/5b9ce41178a8f8f1986ebbf432162f76ead5a39c)
> update api level 21

- lib_nbgl/include/nbgl_content.h
- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/include/nbgl_page.h
- lib_nbgl/include/nbgl_use_case.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_layout_internal.h
- lib_nbgl/src/nbgl_page.c
- lib_nbgl/src/nbgl_use_case.c
The original goal of this PR is to support Tip-Box, as on the attached picture (from https://www.figma.com/design/k9Q6hP0XWAw00AiT6GDb0O/02.-App-SDK?node-id=94-69834&t=ZUjo31oi2l0Y5sc1-4)
To do so, it's necessary to add a up-footer object (and container) in layout layer. This addition enable to regroup other "similar" objects in this up-footer object, like long-press button, horizontal buttons and simple button (in case of button in bottom)
Moreover, to link the content of the tip-box to the centered info), an extended centered info has to be created.
Finally, an nbgl_useCaseAdvancedReview() API is created to be able to use this tip-box in the case illustrated by the attached picture
> Add up footer layout object and tip-box object

- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/include/nbgl_use_case.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to enable automatic computation of number of items per settings page, to optimize this number and avoid static values
> Automatic computation of number of items per settings page

- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/src/nbgl_layout.c
The goal of this PR is to fix missing "Tap To Continue" in transactions (when using the old Use Case or Page API). This was due to a dupplicated usage of footer, both for "Tap to Continue" and then for "Cancel", the second one overriding the first one.
The fix consists in using "Up Footer" instead of Footer, for "Tap to Continue" 
> Fix missing Tap To Continue in transactions

- lib_nbgl/src/nbgl_use_case.c
To be in line with the new Figma designs.
> Updated the wording on the warning screen for blind signing

- lib_nbgl/src/nbgl_use_case.c
> API level 21 cherry-pick for blind signing wording

- include/syscalls.h
- lib_nbgl/include/nbgl_front.h
- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/include/nbgl_types.h
- lib_nbgl/src/nbgl_obj.c
- src/syscalls.c
> Flex: Add nbgl masking syscall

- lib_nbgl/include/nbgl_fonts.h
- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/src/nbgl_draw.c
- lib_nbgl/src/nbgl_fonts.c
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_obj.c
- lib_nbgl/src/nbgl_serialize.c
- unit-tests/lib_nbgl/CMakeLists.txt
- unit-tests/lib_nbgl/nbgl_stubs.c
- unit-tests/lib_nbgl/test_nbgl_screen.c
The goal of this PR is to remove the dependency existing between NBGL and languages:
- ids used to identify localized strings
- Global language_pack variable used in Fonts management library
This is a first necessary step to use NBGL as a common library for OS and Apps.
It only breaks compatibility with the OS (removed field in some objects, and nbgl_refreshUnicodeFont() prototype changed)
> Remove language dependency from NBGL

- lib_nbgl/src/nbgl_obj.c
Fix a progress bar glitch that occured when a modal was displayed over a progress bar.
Example:
[Ledger Flex Review: Suspiciously Good!](https://www.youtube.com/watch?v=xqtdxg4XEAo&t=950s)
> Flex/Stax: Progress bar fix

- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to fix https://github.com/LedgerHQ/ledger-secure-sdk/issues/749 by using the "wrapping" field of Details Context instead of forcing it to false by mistake, for calculation.
> Fix character loss in detail pairs with text wrapping enabled

- lib_nbgl/src/nbgl_fonts.c
- unit-tests/lib_nbgl/test_nbgl_fonts.c
The goal of this PR is to fix an issue in nbgl_textWrapOnNbLines().
This function is intended to create a multi-lines text fitting in the given width and number of lines, wrapping on spaces, and, if the text is too long, the last char is replaced by "...". 
But sometimes, the "..." is too long and the last line doesn't fit in width, so in these case the last 2 characters must be replaced by "..."
> Fix replacement of last char by "..." when using nbgl_textWrapOnNbLines()

- lib_nbgl/include/nbgl_use_case.h
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to add two new Use Cases, for blind signing, in regular and streaming cases.
The prototypes are exactly the same as the non-Blind-Signing ones, the only difference being the warning page preceding the
initial review.
> Blind signing review use cases

- lib_nbgl/include/nbgl_use_case.h
- lib_nbgl/src/nbgl_fonts.c
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to fix 2 issues with two long "value" fields in reviews:
- In case of a "Skippable" review, the last line of value may be out of the area
- In the "Details" view, the last line may be wrongly cut (at "...") if ending with a '\n'
> Fix too long text shortening in details

- .github/workflows/unit_tests.yml
- lib_ux_sync/include/ux_sync.h
- lib_ux_sync/src/ux_sync.c
- unit-tests/lib_ux_sync/CMakeLists.txt
- unit-tests/lib_ux_sync/README.md
- unit-tests/lib_ux_sync/nbgl_stubs.c
- unit-tests/lib_ux_sync/test_ux_sync.c
The goal of this PR is to add unit-tests for UX Sync library, in order to improve code coverage of this library
- [*] Tests
> Add UX Sync unit tests

- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_obj.c
- lib_nbgl/src/nbgl_screen.c
The goal is to fix a potential issue when using long-press button.
If the touch is releasead when the first "step" is drawn, this step is not deleted in the progress bar
> Fix Progress Bar issue in long-press when releasing

- include/syscalls.h
- lib_nbgl/include/nbgl_screen.h
- src/syscalls.c
Rename defines for experimental display features on Stax.
- `HAVE_DISPLAY_FAST_MODE` -> `HAVE_STAX_DISPLAY_FAST_MODE`
- `HAVE_CONFIGURABLE_DISPLAY_FAST_MODE` -> `HAVE_STAX_CONFIG_DISPLAY_FAST_MODE`
> Stax: Rename experimental Stax display defines

- lib_nbgl/src/nbgl_layout_navigation.c
The goal of this PR is to fix a bug impacting page indicator display ("<i> of <N>") when using more than 9 pages. 
In this case the width of the text area is not suffisiant and the indicator is broken on 2 lines.
> Fix bad page indicator display when more than 9 pages

- lib_nbgl/src/nbgl_fonts.c
- unit-tests/lib_nbgl/test_nbgl_fonts.c
The goal of this PR is to fix text shortening (nbgl_textWrapOnNbLines()) in some corner cases ("..." being longer than 2 chars)
> Fix wrong text shortening in some corner cases ("..." being longer than 2 chars)

- lib_nbgl/src/nbgl_fonts.c
- unit-tests/lib_nbgl/test_nbgl_fonts.c
The goal of this PR is to fix text shortening (nbgl_textWrapOnNbLines()) in some corner cases ("..." being longer than 2 chars)
> Fix wrong text shortening in some corner cases ('...' being longer than 2 chars)

- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to unify the wording of Blind Signing warnings in review flow, whatever the "operation" is: transaction or message)
> Unify Blind Signing Warning wording

- .github/workflows/build_rust_sdk.yml
Update the CI to build Rust SDK when new PR is proposed
> Build Rust SDK for each PR

- lib_nbgl/include/nbgl_use_case.h
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to add extended version of nbgl_useCaseGetNbTagValuesInPage() to handle skippable review.
> Add extended version of nbgl_useCaseGetNbTagValuesInPage() to handle skippable review

- include/os_nvm.h
- src/syscalls.c
This PR update syscall for nvram return status.
- [ x] Breaking change (change that is not backwards-compatible and/or changes current functionality)
Return status code for one syscall.
> Add Return status to syscall for nvram

- lib_nbgl/doc/nbgl_use_case.dox
- lib_nbgl/include/nbgl_use_case.h
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to add navigable content use case (nbgl_useCaseNavigableContent) to replace depracated settings use case (nbgl_useCaseSettings)
> Add navigable content use case to replace settings use case

- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to fix crashing address review after a blind signing review. This issue is due to a shared context between   blind signing review and address review, leading to a wrong release of layout. The fix consists in not using shared context anymore.
> Fix crashing address review after a blind signing review

- include/os_app.h
Remove padding and holes from this structure.
- [X ] Bugfix (non-breaking change that solves an issue)
> Move flags member of the application structure

- Makefile.defines
- Makefile.rules
- Makefile.standard_app
Now only uses clang for all steps of the build instead of the assembly of .S files and binary linking being delegated to GCC.
> Full clang build for standard apps

- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to disable "swipe to review" text in first page of review if using a Tip-Box.
It also fixes a potential issue when touching Tip-Box, with PIC()
> No "swipe to review" in first page of review if using a Tip-Box

- include/cx_stubs.h
- include/ox_aes.h
- lib_cxng/cx.export
- lib_cxng/include/lcx_aes_siv.h
- lib_cxng/src/cx_aes.c
- lib_cxng/src/cx_aes_siv.c
- lib_cxng/src/cx_cipher.h
- src/cx_stubs.S
- src/syscalls.c
Add new AES SIV function to reset the AES copro.
> cx_aes_siv: Add new function to reset AES hw copro

- lib_nbgl/include/nbgl_content.h
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to display QR Code title different from QR Code URL in alias
> Display QR Code title different from URL in alias

- lib_nbgl/include/nbgl_content.h
- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_page.c
- lib_nbgl/src/nbgl_use_case.c
Cherry-pick NBGL improvements from Master to API_LEVEL_21:
- Create a QR Code type of modal window for Tag/Value alias
- No "swipe to review" in first page of review if using a Tip-Box
- Add extension to INFOS_LIST to enable alias for some info types
> Cherry pick nbgl level21

- .github/workflows/build_rust_sdk.yml
When compiling the Rust SDK, use the PR branch of the C SDK (and not the master branch as it will not test the PR modifications).
> Use current PR branch when compiling C SDK

- lib_standard_app/main.c
See #786 for description of issue this PR fixes
> Fix error when setting `DISABLE_STANDARD_USB = 1` in Makefile

- lib_standard_app/main.c
> Fix error when setting `DISABLE_STANDARD_USB = 1` in standard app Makefile - cherry pick API_LEVEL_LNS

- lib_standard_app/main.c
> Fix error when setting `DISABLE_STANDARD_USB = 1` in standard app Makefile - cherry pick API_LEVEL_5

- lib_standard_app/main.c
> Fix error when setting `DISABLE_STANDARD_USB = 1` in standard app Makefile - cherry pick API_LEVEL_21

- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to fix minor issues in infos-list with alias display:
- whole row as touchable area
- chevron icon
- tune when coming back from info list
> Minor fixes in infos-list with alias display (touchable area, icon, tune)

- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_touch.c
The goal of this PR is to improve layout layer of NBGL to factorize code in Bolos UX.
This shouldn't concern any application.
Prototype of `nbgl_layoutAddLargeCaseText()` has changed, but it is not used by any app (on LegderHQ)
> NBGL improvements to factorize code

- lib_cxng/include/lcx_math.h
The current implementation `cx_math_is_zero` does not run in constant time, but it's not documented; this could lead to vulnerabilities if used in cryptographic code in apps.
This PR replaces it with a constant time implementation to avoid any such risks.
> Make cx_math_is_zero run in constant time

- lib_nbgl/src/nbgl_step.c
In nbgl_step.c `actionCallback`, `onActionCallback` was called without being checked, leading to crash if the callback is NULL. This commit adds the relevant checks.
> NBGL Nano: Check onActionCallback validity

- lib_nbgl/include/nbgl_use_case.h
> Make the info list property in nbgl_tipBox_t non-const - API_LEVEL_22

- lib_nbgl/src/nbgl_layout_keypad_nanos.c
- lib_nbgl/src/nbgl_obj_keypad_nanos.c
Fix pin keypad behavior to pre-nbgl.
> Fweo 1254 pinpad nano

- lib_nbgl/src/nbgl_layout_keypad_nanos.c
- lib_nbgl/src/nbgl_obj_keypad_nanos.c
Fix pin keypad behavior to pre-nbgl.
> Cherry pick fixes for pinpad nanos

- Makefile.standard_app
- include/os_io_nfc.h
- include/seproxyhal_protocol.h
- lib_standard_app/io.c
- src/os_io_nfc.c
- src/os_io_seproxyhal.c
- src/os_io_task.c
Add application support for NFC in reader mode in `os_io_nfc`
> Add NFC reader mode support

- Makefile.defines
- include/os_id.h
- include/syscalls.h
- src/syscalls.c
The goal of this PR is to Integrate and remove HAVE_MCU_SERIAL_STORAGE (always defined) flag.
This is a PR of code cleaning.
It is not planned to support products or flavors without this feature, so the flag is useless (it was defined only for Nanos but it was a mistake, because available on all products)
- [*] Other (for changes that might not fit in any category)
> Integrate HAVE_MCU_SERIAL_STORAGE flag code

- lib_nbgl/src/nbgl_step.c
The goal of this PR is to fix case when multi-pages text contains '\n' at page break, creating a non expected empty line as the first line of the next page.
> Fix case when multi-pages text contains '\n' at page break

- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/include/nbgl_page.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_page.c
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to implement the ability to call nbgl_useCaseSpinner() several time in a raw. It enables to "turn" the corner, for example when used in some steps of a long mono-process, preventing the automatic update.
> Incrementing spinner Use Case when called multiple times

- Makefile.app_params
Apps params computation did not allow an empty icon.
> App params: Allow empty icon when computing app params

- lib_nbgl/doc/nbgl_use_case.dox
- lib_nbgl/include/nbgl_use_case.h
- lib_nbgl/src/nbgl_use_case.c
Add support for customized fields:
- `reportUrl`
- `providerMessage`
Handle thesee fields in the different Warning Screens
Update the doc accordingly
> Add W3C customized fields (URL, ProviderMsg)

- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/include/nbgl_page.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_page.c
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to implement the ability to call nbgl_useCaseSpinner() several time in a raw. It enables to "turn" the corner, for example when used in some steps of a long mono-process, preventing the automatic update.
This is a cherry-pick on API LEVEL 22
> Incrementing spinner use case

- lib_nbgl/src/nbgl_step.c
- lib_nbgl/src/nbgl_use_case_nanos.c
The goal of this PR is to improve Nano NBGL, to support 2 features:
- "Skip" feature in streamed review (on demand), to be able to go directly to approval
- Truncate title line when using multi-pages steps. If the title is greater than one line, it is truncated by it's middle (replaced by "...")
-
> Nano NBGL improvements (support Skip & truncate titles) level 22

- lib_nbgl/src/nbgl_use_case.c
- Update Potential Risk icon to WARNING
- Replace "not available" by "unavailable
- Fix warning screen in case of Blind Signing + Issue
> Update W3C screens

- lib_nbgl/doc/nbgl_use_case_nanos.dox
- lib_nbgl/src/nbgl_use_case_nanos.c
Add missing API `nbgl_useCaseAdvancedReview` for Nano on NBGL.
This is a 1st version, before the Product design are finalized.
> Add 1st version of AdvancedReiwew for Nano on NBGL

- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/src/nbgl_layout.c
The goal of this PR is to add nbgl_layoutAddLeftContent() on API level 22
> Add nbgl_layoutAddLeftContent() on API level 22

- lib_nbgl/src/nbgl_layout_internal.h
The goal of this PR is to fix partially erased top right icon on API level 22
> Fix partially erased top right icon on level 22

- lib_nbgl/src/nbgl_touch.c
The goal of this PR is to fix untouchable top-right button, because swipable container.
By parsing at first last drawn object, we are sure that touch event is properly processed.
> Fix untouchable top-right button, because swipable container

- tools/elf_info.py
This tool will display the following:
```
$ tools/elf_info.py -i /work/apps/app-cardano/bin/app.elf -v
[INFO] Parsing binary '/work/apps/app-cardano/bin/app.elf'
---
[INFO] app_name:     'Cardano ADA'
[INFO] app_version:  '7.2.2'
[INFO] sdk_graphics: 'nbgl'
---
[INFO] sdk_name:     'ledger-secure-sdk'
[INFO] sdk_version:  'v22.4.0'
[DEBUG] api_level:   '22'
[DEBUG] sdk_hash:    '1838f8b1986a79d77fda95df1fbd9c09aa61ca76'
---
[INFO] target:       'flex'
[INFO] target_id:    '0x33300004'
[INFO] target_name:  'TARGET_FLEX'
```
> Add tool to display elf metadata from ledger sections

- lib_nbgl/include/nbgl_content.h
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to enable giving a title for opened page when alias is touched in INFO_LIST_ALIAS case
> Use given title for opened page when alias is touched in INFO_LIST_ALIAS case

- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/src/nbgl_layout.c
This PR aims to rework add progress bar layout for wallet.  This rework will add a subtitle option when creating a progress bar.
Also add a new function called add nbgl_layoutUpdateProgressBar.
> Kmc rework progress bar

- .github/workflows/unit_tests.yml
- Makefile.rules
- doc/Doxyfile
- doc/mainpage.dox
- include/errors.h
- lib_alloc/doc/mainpage.dox
- lib_alloc/mem_alloc.c
- lib_alloc/mem_alloc.h
- unit-tests/lib_alloc/CMakeLists.txt
- unit-tests/lib_alloc/README.md
- unit-tests/lib_alloc/test_mem_alloc.c
The goal of this PR is to implement a dynamic memory allocator, usable at least by the applications.
Each application can provide a buffer to be used as dynamic allocation buffer, and then use mem_alloc() and mem_free() to allocate and release memory chunks
A full explanation is available in https://ledgerhq.atlassian.net/wiki/spaces/FW/pages/5371068584/Study+-+Dynamic+Storage+Allocation
> Add dynamic memory allocator

- tools/ttf2inc.py
The goal of this PR is to fix an issue with ttf2inc with chars in RLE format and 4BPP (nor properly aligned on multiple of 4)
> Fix issue with ttf2inc with chars in RLE format and 4BPP

- include/os_settings.h
- include/syscalls.h
- src/syscalls.c
The goal of this PR is to add a new syscall enabling to set in the OS the RK backup state during onboarding
New syscall
> Adapt for RK backup state

- lib_alloc/mem_alloc.c
Causes :red_circle: CI during static analysis on apps that use the lib_alloc.
> Fix deadcode.DeadStores clang analyzer warning in lib_alloc

- lib_alloc/mem_alloc.c
> Fix deadcode.DeadStores clang analyzer warning in lib_alloc - API_LEVEL_22

- lib_nbgl/include/nbgl_use_case.h
- lib_nbgl/src/nbgl_use_case.c
- lib_nbgl/src/nbgl_use_case_nanos.c
The goal of this PR is to memorize streaming operation type for Nano, and better manage finish title, with default values if NULL
> Memorize streaming op type and manage finish title

- lib_nbgl/include/nbgl_content.h
- lib_nbgl/include/nbgl_use_case.h
- lib_nbgl/src/nbgl_use_case.c
- lib_nbgl/src/nbgl_use_case_nanos.c
The goal of this PR is to 
- memorize streaming operation type for Nano
- better manage finish title, with default values if NULL
- support centered info as tag/value pair for Nano review
> Patches to merge in API level 22

- lib_nbgl/src/nbgl_obj.c
The goal of this PR is to fix auto-truncation to nbLines when last line contains a \n
> Fix auto-truncate to nbLines when last line contains a \n

- lib_blewbxx/include/ble_ledger.h
- lib_blewbxx/include/ble_ledger_profile_apdu.h
- lib_blewbxx/include/ble_ledger_types.h
- lib_blewbxx/src/ble_ledger.c
- lib_blewbxx/src/ble_ledger_profile_apdu.c
- lib_stusb/include/usbd_ledger_ccid.h
- lib_stusb/include/usbd_ledger_hid.h
- lib_stusb/include/usbd_ledger_hid_u2f.h
- lib_stusb/include/usbd_ledger_types.h
- lib_stusb/include/usbd_ledger_webusb.h
- lib_stusb/src/usbd_ledger_ccid.c
- lib_stusb/src/usbd_ledger_hid.c
- lib_stusb/src/usbd_ledger_hid_u2f.c
- lib_stusb/src/usbd_ledger_webusb.c
Fix `BLE_LEDGER_is_busy()` and cleanup the signature.
> [lib_ble]: fix is_busy, cleanup types

- .github/workflows/build_all_c_apps.yml
- .github/workflows/check_clang_static_analyzer.yml
- Makefile.rules
- Makefile.rules_generic
- lib_standard_app/main.c
- lib_standard_app/main_std_app.h
- Add generic standard app main header file (`main_std_app.h`) to be used by the apps
- Add rules allowing to compile Apps based on the pre-defined use-cases. 
For example, in `app-ethereum`: `make dbg_use_test_keys`, instead of giving the whole set of flags
> Make improvements

- lib_nbgl/src/nbgl_obj_pool.c
The goal of this PR is to adapt the maximum size of an NBGL object in object pool.
Currently it's tool smal when using a button in Nano case, and end of objects may be corrupter
> Adapt the maximum size of an NBGL object in object pool

- lib_nbgl/src/nbgl_layout.c
The goal of this PR is to fix bottom margin of nbgl_layoutAddText() function (for example for settings->version in apps)
[ ] TARGET_API_LEVEL: API_LEVEL_22
[x] TARGET_API_LEVEL: API_LEVEL_23
Remember:
- In such case, there is no other solution than do the operation manually...
> Fix bottom margin of nbgl_layoutAddText() function

- lib_nbgl/include/nbgl_obj.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_layout_internal.h
- lib_nbgl/src/nbgl_screen.c
The goal of this PR is to reset long-press button to 0 when overriden by another screen (a modal, for example lock/battery alert...).
For this we use a boolean in Progress Bar structure to indicate that it's a progress that needs to be reset. 
Then, when pushing  a new one on top of the screen, its state is reset to 0.
Previously it was done by sending a fake "touch release" to the screen, when pushing a new one on top of it, but it cannot work with App screens overriden by UX screens.
> Reset long-press button when overriden by another screen

- include/os_ux.h
`lock_delay` struct shall always be available in `bolos_ux_params_t`, whatever the device.
> lock_delay shall be always available in the union

- lib_nbgl/include/nbgl_content.h
- lib_nbgl/include/nbgl_layout.h
- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_use_case.c
- tests/screenshots/flows/wallet/app-sdk/flow_address_verif.json
- tests/screenshots/src/apps/app_ethereum_verify_addr.c
- tests/screenshots/src/apps/apps_api.h
- tests/screenshots/src/main/json_scenario.c
- tests/screenshots/src/main/json_scenario.h
For multi-sig feature, we need to display a list of signers when pressing the alias (>) of a specific pair.
This PR also adds an improvement, to gather tag/value pairs with the address in "address review" if it fits in a signe page.
> Address verif improvements 23

- lib_nbgl/src/nbgl_obj.c
Add a protection to avoid having an app trying to redraw for instance an UX screen, which will fail anyway.
> [lib_nbgl]: Add a protection to forbid drawing a screen owned by someone else

- lib_blewbxx/src/ble_ledger.c
This PR prevents a BLE pairing reset on a non-seeded device at the end of the onboarding and at the end of an update.
> Fix ble pairing

- io_legacy/include/os_io_legacy.h
- lib_nfc/src/nfc_ledger.c
- lib_stusb/src/usbd_ledger_hid_u2f.c
> Several fixes for recent SDK changes

- io_legacy/src/os_io_legacy.c
- lib_nbgl/src/nbgl_layout_keypad.c
- lib_nbgl/src/nbgl_use_case_nanos.c
Fix use_case for Nano devices:
- Add a PIC macro to access strings buffer
- Add support for TAG_VALUE_LIST_ALIAS in extensions
- Cleanup code for better readility
In addition:
- Fix few scan-build errors (from app-tester checks: https://github.com/LedgerHQ/ledger-app-tester/actions/runs/16767813227)
[x] TARGET_API_LEVEL: API_LEVEL_24
> Fix memory buffer access

- lib_nbgl/src/nbgl_use_case.c
When computing the switch height, subText can be NULL
> Manual cherry-pick for 'switch subText can be NULL'

- lib_nbgl/src/nbgl_use_case.c
When computing the switch height, subText can be NULL
> switch subText can be NULL

- .github/workflows/scripts/pr_check.py
Add git user config (name, email) in auto-cherr-pick
> Configure Git user identity for the cherry-pick

- lib_nbgl/doc/nbgl_use_case.dox
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to fix switches list height computation in NBGL Use Case.
It also fixes a minor issue in custom warning review.
> Fix switches list height computation in NBGL Use Case

- lib_nbgl/fonts/config-open_sans_extrabold_11.ini
- lib_nbgl/fonts/config-open_sans_regular_11.ini
The goal of this PR is to fix https://ledger.slack.com/archives/C023GBQCULX/p1754387930803479.
This issue has been seen on some Unicode (non-Ascii) characters, that are 1 pixel lower than the other chars.
> Fix vertical alignement of some Unicode chars on NanoX/S+

- lib_nbgl/src/nbgl_layout.c
- tests/screenshots/flows/wallet/app-sdk/flow_w3c_dapp.json
The goal of this PR is to fix https://ledgerhq.atlassian.net/browse/FWEO-1469
Cherry pick from master
> Fix FWEO-1394 - Transaction field disclosure should be clickable on the full row, not only the chevron icon

- lib_nbgl/nbgl.export
- lib_nbgl/src/nbgl_layout_nanos.c
- src/nbgl_stubs.S
The goal of this PR is to fix missing nbgl_getTextMaxLenAndWidth() in OS trampoline. It is so forbidden to use in Apps. So it's better to remove it from nbgl_stubs.S
It solves https://ledgerhq.atlassian.net/browse/B2CA-2257
NO cherry-pick in API Level >=25
> Fix missing nbgl_getTextMaxLenAndWidth in OS

- src/pic.c
In the context of an OSU, the `pic` function used to link addresses
in RAM. Those addresses are already known at compile time. Applying this
relocation triggered incorrect behaviors.
Remember:
> OSU: PIC - Disable relocation of addresses in RAM

- lib_standard_app/main.c
App storage init has been lost during io-revamp, bring back the init.
Initial PR: https://github.com/LedgerHQ/ledger-secure-sdk/pull/902/
[x] TARGET_API_LEVEL: API_LEVEL_24
Remember:
> app_storage: bring back init

- lib_nbgl/src/nbgl_layout.c
- lib_nbgl/src/nbgl_layout_internal.h
The goal of this PR is to create a real screen stack in NBGL layout layer. 
Currenty, the mechanism is incomplete at this level of NBGL, and it assumes that the layers are always released at the reverse order of their creation.
> Implement a real screen stack in NBGL layout layer

- lib_nbgl/src/nbgl_obj.c
The screen resolution on APEX is much smaller than on Flex/Stax, which causes problems when displaying text across the entire screen.
When such a case occur, LOG_FATAL function is called, causing the build to fail.
When we build screenshots, we don't want the build to fail, we want an error message to be displayed instead, making it possible for translators to make the text shorter.
This PR fix that issue.
> Fix whole screen issue when building screenshots

- lib_nbgl/src/nbgl_obj.c
The screen resolution on APEX is much smaller than on Flex/Stax, which causes problems when displaying text across the entire screen.
When such a case occur, LOG_FATAL function is called, causing the build to fail.
When we build screenshots, we don't want the build to fail, we want an error message to be displayed instead, making it possible for translators to make the text shorter.
This PR fix that issue.
> reFix whole screen issue when building screenshots

- include/errors.h
- include/status_words.h
Default list of Status Words
[X] TARGET_API_LEVEL: API_LEVEL_24
> Define default Status Word values

- lib_nbgl/src/nbgl_layout.c
The goal of this PR is to fix missing PIC in NBGL Layout tap action text
Remember:
> Fix missing PIC in NBGL Layout tap action text

- lib_nbgl/src/nbgl_layout.c
(cherry picked from commit 10cf12eca28083b2e1af2954996f2a931cb46fc4)
Remember:
- The merge will ALWAYS be a manual …
> NBGL layout: Fix missing PIC in "addLeftContent"

- lib_nbgl/src/nbgl_fonts.c
- lib_nbgl/src/nbgl_obj.c
- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to fix https://ledgerhq.atlassian.net/browse/B2CA-2296
This is done by fixing the computation of nbgl_getTextMaxLenInNbLines() in case of a mix of \n and wrapping
But also by removing the usage of "..." in case the last line ends with a \n
But must of this fix is in the OS part, so a new OS will be necessary
[x] TARGET_API_LEVEL: API_LEVEL_24
This will only create the PR with cherry-picks, ready to be reviewed and …
> Fix Rendering and Line-breaking EIP-191 message

- lib_nbgl/src/nbgl_layout.c
The goal of this PR is to fix deleted line when releasing long press button
Remember:
> Fix deleted line when releasing long press button

- lib_nbgl/src/nbgl_screen.c
The goal of this PR is to fix a crash happening when the screensaver starts on top of an App (using NBGL) on Nano (S+, X)
This is done by checking that the nbgl_screenHandler() doesn't call the ticker handler of a screen not belonging to its task (UX for UX, App for App)
> Fix screensaver on app issue (Level 24)

- lib_nbgl/src/nbgl_use_case.c
The goal of this PR is to fix missing "Skip" in first page of streaming review
[x] TARGET_API_LEVEL: API_LEVEL_24
Remember:
> Fix missing "Skip" in first page of streaming review

- lib_nbgl/src/nbgl_fonts.c
The goal of this PR is to "support" Unicode chars in Apps, by considering them as "empty", instead of crashing when trying to get them from Language pack when encountered.
This fix will be in shared.elf so needs to be integrated in OS to be used.
(Cherry-pick from master)
> Avoid to crash when parsing strings with Unicode in Apps

- lib_nbgl/include/nbgl_use_case.h
- lib_nbgl/src/nbgl_use_case.c
- lib_nbgl/src/nbgl_use_case_nanos.c
Automated update from #1214 (Update nbgl_useCaseKeypadXXX definitions)
> [AUTO_UPDATE] Branch API_LEVEL_24

- lib_nbgl/doc/nbgl_use_case.dox
- lib_nbgl/doc/nbgl_use_case_nanos.dox
- lib_nbgl/include/nbgl_use_case.h
- lib_nbgl/src/nbgl_use_case.c
- lib_nbgl/src/nbgl_use_case_nanos.c
Remove
- `nbgl_useCaseKeypadPIN`
- `nbgl_useCaseKeypadDigits`
Now, a sngloe API is available: `nbgl_useCaseKeypad`
> remove deprecated keypad functions
